// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AdminUsersColumns holds the columns for the "admin_users" table.
	AdminUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "first_name", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "last_name", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
	}
	// AdminUsersTable holds the schema information for the "admin_users" table.
	AdminUsersTable = &schema.Table{
		Name:       "admin_users",
		Columns:    AdminUsersColumns,
		PrimaryKey: []*schema.Column{AdminUsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "adminuser_status",
				Unique:  false,
				Columns: []*schema.Column{AdminUsersColumns[12]},
			},
		},
	}
	// CurrenciesColumns holds the columns for the "currencies" table.
	CurrenciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 3},
		{Name: "name", Type: field.TypeString},
		{Name: "symbol", Type: field.TypeString, Default: ""},
		{Name: "precision", Type: field.TypeInt, Default: 2},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// CurrenciesTable holds the schema information for the "currencies" table.
	CurrenciesTable = &schema.Table{
		Name:       "currencies",
		Columns:    CurrenciesColumns,
		PrimaryKey: []*schema.Column{CurrenciesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "currency_is_active",
				Unique:  false,
				Columns: []*schema.Column{CurrenciesColumns[12]},
			},
		},
	}
	// LocalesColumns holds the columns for the "locales" table.
	LocalesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 8},
		{Name: "name", Type: field.TypeString},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// LocalesTable holds the schema information for the "locales" table.
	LocalesTable = &schema.Table{
		Name:       "locales",
		Columns:    LocalesColumns,
		PrimaryKey: []*schema.Column{LocalesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "locale_is_active",
				Unique:  false,
				Columns: []*schema.Column{LocalesColumns[10]},
			},
		},
	}
	// PermissionsColumns holds the columns for the "permissions" table.
	PermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "resource", Type: field.TypeString},
		{Name: "action", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Default: ""},
	}
	// PermissionsTable holds the schema information for the "permissions" table.
	PermissionsTable = &schema.Table{
		Name:       "permissions",
		Columns:    PermissionsColumns,
		PrimaryKey: []*schema.Column{PermissionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "permission_resource_action",
				Unique:  true,
				Columns: []*schema.Column{PermissionsColumns[8], PermissionsColumns[9]},
			},
		},
	}
	// RegionsColumns holds the columns for the "regions" table.
	RegionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "locale", Type: field.TypeString, Size: 8},
		{Name: "currency_code", Type: field.TypeString, Size: 3},
		{Name: "tax_inclusive", Type: field.TypeBool, Default: false},
		{Name: "countries", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive"}, Default: "active"},
	}
	// RegionsTable holds the schema information for the "regions" table.
	RegionsTable = &schema.Table{
		Name:       "regions",
		Columns:    RegionsColumns,
		PrimaryKey: []*schema.Column{RegionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "region_status",
				Unique:  false,
				Columns: []*schema.Column{RegionsColumns[13]},
			},
		},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "is_system", Type: field.TypeBool, Default: false},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "role_is_system",
				Unique:  false,
				Columns: []*schema.Column{RolesColumns[11]},
			},
		},
	}
	// StoresColumns holds the columns for the "stores" table.
	StoresColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "site_type", Type: field.TypeEnum, Enums: []string{"corporate", "store", "hybrid"}, Default: "store"},
		{Name: "default_locale", Type: field.TypeString, Size: 8, Default: "en"},
		{Name: "default_currency", Type: field.TypeString, Size: 3, Default: "USD"},
		{Name: "feature_flags", Type: field.TypeJSON, Nullable: true},
		{Name: "timezone", Type: field.TypeString, Default: "UTC"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "maintenance"}, Default: "active"},
	}
	// StoresTable holds the schema information for the "stores" table.
	StoresTable = &schema.Table{
		Name:       "stores",
		Columns:    StoresColumns,
		PrimaryKey: []*schema.Column{StoresColumns[0]},
	}
	// TaxRatesColumns holds the columns for the "tax_rates" table.
	TaxRatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "country_code", Type: field.TypeString, Nullable: true, Size: 2},
		{Name: "rate", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric(5,4)"}},
		{Name: "name", Type: field.TypeString},
		{Name: "priority", Type: field.TypeInt, Default: 0},
		{Name: "region_id", Type: field.TypeInt},
	}
	// TaxRatesTable holds the schema information for the "tax_rates" table.
	TaxRatesTable = &schema.Table{
		Name:       "tax_rates",
		Columns:    TaxRatesColumns,
		PrimaryKey: []*schema.Column{TaxRatesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tax_rates_regions_tax_rates",
				Columns:    []*schema.Column{TaxRatesColumns[12]},
				RefColumns: []*schema.Column{RegionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "taxrate_region_id",
				Unique:  false,
				Columns: []*schema.Column{TaxRatesColumns[12]},
			},
			{
				Name:    "taxrate_country_code",
				Unique:  false,
				Columns: []*schema.Column{TaxRatesColumns[8]},
			},
		},
	}
	// RoleAdminsColumns holds the columns for the "role_admins" table.
	RoleAdminsColumns = []*schema.Column{
		{Name: "role_id", Type: field.TypeInt},
		{Name: "admin_user_id", Type: field.TypeInt},
	}
	// RoleAdminsTable holds the schema information for the "role_admins" table.
	RoleAdminsTable = &schema.Table{
		Name:       "role_admins",
		Columns:    RoleAdminsColumns,
		PrimaryKey: []*schema.Column{RoleAdminsColumns[0], RoleAdminsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "role_admins_role_id",
				Columns:    []*schema.Column{RoleAdminsColumns[0]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "role_admins_admin_user_id",
				Columns:    []*schema.Column{RoleAdminsColumns[1]},
				RefColumns: []*schema.Column{AdminUsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// RolePermissionsColumns holds the columns for the "role_permissions" table.
	RolePermissionsColumns = []*schema.Column{
		{Name: "role_id", Type: field.TypeInt},
		{Name: "permission_id", Type: field.TypeInt},
	}
	// RolePermissionsTable holds the schema information for the "role_permissions" table.
	RolePermissionsTable = &schema.Table{
		Name:       "role_permissions",
		Columns:    RolePermissionsColumns,
		PrimaryKey: []*schema.Column{RolePermissionsColumns[0], RolePermissionsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "role_permissions_role_id",
				Columns:    []*schema.Column{RolePermissionsColumns[0]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "role_permissions_permission_id",
				Columns:    []*schema.Column{RolePermissionsColumns[1]},
				RefColumns: []*schema.Column{PermissionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AdminUsersTable,
		CurrenciesTable,
		LocalesTable,
		PermissionsTable,
		RegionsTable,
		RolesTable,
		StoresTable,
		TaxRatesTable,
		RoleAdminsTable,
		RolePermissionsTable,
	}
)

func init() {
	TaxRatesTable.ForeignKeys[0].RefTable = RegionsTable
	RoleAdminsTable.ForeignKeys[0].RefTable = RolesTable
	RoleAdminsTable.ForeignKeys[1].RefTable = AdminUsersTable
	RolePermissionsTable.ForeignKeys[0].RefTable = RolesTable
	RolePermissionsTable.ForeignKeys[1].RefTable = PermissionsTable
}
