// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AdminUsersColumns holds the columns for the "admin_users" table.
	AdminUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "first_name", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "last_name", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
	}
	// AdminUsersTable holds the schema information for the "admin_users" table.
	AdminUsersTable = &schema.Table{
		Name:       "admin_users",
		Columns:    AdminUsersColumns,
		PrimaryKey: []*schema.Column{AdminUsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "adminuser_status",
				Unique:  false,
				Columns: []*schema.Column{AdminUsersColumns[12]},
			},
		},
	}
	// BlogPostsColumns holds the columns for the "blog_posts" table.
	BlogPostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "author_admin_id", Type: field.TypeInt},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"draft", "published", "archived"}, Default: "draft"},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
	}
	// BlogPostsTable holds the schema information for the "blog_posts" table.
	BlogPostsTable = &schema.Table{
		Name:       "blog_posts",
		Columns:    BlogPostsColumns,
		PrimaryKey: []*schema.Column{BlogPostsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "blogpost_status",
				Unique:  false,
				Columns: []*schema.Column{BlogPostsColumns[10]},
			},
			{
				Name:    "blogpost_author_admin_id",
				Unique:  false,
				Columns: []*schema.Column{BlogPostsColumns[9]},
			},
		},
	}
	// BlogPostTranslationsColumns holds the columns for the "blog_post_translations" table.
	BlogPostTranslationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "locale", Type: field.TypeString, Size: 8},
		{Name: "title", Type: field.TypeString},
		{Name: "excerpt", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "content", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "seo_title", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "seo_desc", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "blog_post_id", Type: field.TypeInt},
	}
	// BlogPostTranslationsTable holds the schema information for the "blog_post_translations" table.
	BlogPostTranslationsTable = &schema.Table{
		Name:       "blog_post_translations",
		Columns:    BlogPostTranslationsColumns,
		PrimaryKey: []*schema.Column{BlogPostTranslationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "blog_post_translations_blog_posts_translations",
				Columns:    []*schema.Column{BlogPostTranslationsColumns[14]},
				RefColumns: []*schema.Column{BlogPostsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "blogposttranslation_blog_post_id_locale",
				Unique:  true,
				Columns: []*schema.Column{BlogPostTranslationsColumns[14], BlogPostTranslationsColumns[8]},
			},
		},
	}
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "parent_id", Type: field.TypeInt, Nullable: true},
		{Name: "position", Type: field.TypeInt, Default: 0},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "category_parent_id",
				Unique:  false,
				Columns: []*schema.Column{CategoriesColumns[9]},
			},
		},
	}
	// CategoryTranslationsColumns holds the columns for the "category_translations" table.
	CategoryTranslationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "locale", Type: field.TypeString, Size: 8},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "category_id", Type: field.TypeInt},
	}
	// CategoryTranslationsTable holds the schema information for the "category_translations" table.
	CategoryTranslationsTable = &schema.Table{
		Name:       "category_translations",
		Columns:    CategoryTranslationsColumns,
		PrimaryKey: []*schema.Column{CategoryTranslationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "category_translations_categories_translations",
				Columns:    []*schema.Column{CategoryTranslationsColumns[11]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "categorytranslation_category_id_locale",
				Unique:  true,
				Columns: []*schema.Column{CategoryTranslationsColumns[11], CategoryTranslationsColumns[8]},
			},
		},
	}
	// CollectionsColumns holds the columns for the "collections" table.
	CollectionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"draft", "published", "archived"}, Default: "draft"},
	}
	// CollectionsTable holds the schema information for the "collections" table.
	CollectionsTable = &schema.Table{
		Name:       "collections",
		Columns:    CollectionsColumns,
		PrimaryKey: []*schema.Column{CollectionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "collection_status",
				Unique:  false,
				Columns: []*schema.Column{CollectionsColumns[9]},
			},
		},
	}
	// CollectionTranslationsColumns holds the columns for the "collection_translations" table.
	CollectionTranslationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "locale", Type: field.TypeString, Size: 8},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "collection_id", Type: field.TypeInt},
	}
	// CollectionTranslationsTable holds the schema information for the "collection_translations" table.
	CollectionTranslationsTable = &schema.Table{
		Name:       "collection_translations",
		Columns:    CollectionTranslationsColumns,
		PrimaryKey: []*schema.Column{CollectionTranslationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "collection_translations_collections_translations",
				Columns:    []*schema.Column{CollectionTranslationsColumns[11]},
				RefColumns: []*schema.Column{CollectionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "collectiontranslation_collection_id_locale",
				Unique:  true,
				Columns: []*schema.Column{CollectionTranslationsColumns[11], CollectionTranslationsColumns[8]},
			},
		},
	}
	// CurrenciesColumns holds the columns for the "currencies" table.
	CurrenciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 3},
		{Name: "name", Type: field.TypeString},
		{Name: "symbol", Type: field.TypeString, Default: ""},
		{Name: "precision", Type: field.TypeInt, Default: 2},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// CurrenciesTable holds the schema information for the "currencies" table.
	CurrenciesTable = &schema.Table{
		Name:       "currencies",
		Columns:    CurrenciesColumns,
		PrimaryKey: []*schema.Column{CurrenciesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "currency_is_active",
				Unique:  false,
				Columns: []*schema.Column{CurrenciesColumns[12]},
			},
		},
	}
	// CustomersColumns holds the columns for the "customers" table.
	CustomersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "phone", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "first_name", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "last_name", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "password_hash", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled", "guest"}, Default: "active"},
		{Name: "default_currency", Type: field.TypeString, Size: 3, Default: "USD"},
		{Name: "default_locale", Type: field.TypeString, Size: 8, Default: "en"},
	}
	// CustomersTable holds the schema information for the "customers" table.
	CustomersTable = &schema.Table{
		Name:       "customers",
		Columns:    CustomersColumns,
		PrimaryKey: []*schema.Column{CustomersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "customer_status",
				Unique:  false,
				Columns: []*schema.Column{CustomersColumns[13]},
			},
		},
	}
	// CustomerAddressesColumns holds the columns for the "customer_addresses" table.
	CustomerAddressesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "first_name", Type: field.TypeString, Default: ""},
		{Name: "last_name", Type: field.TypeString, Default: ""},
		{Name: "company", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "address1", Type: field.TypeString, Default: ""},
		{Name: "address2", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "city", Type: field.TypeString, Default: ""},
		{Name: "province", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "postal_code", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "country_code", Type: field.TypeString, Default: ""},
		{Name: "phone", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "is_default_shipping", Type: field.TypeBool, Default: false},
		{Name: "is_default_billing", Type: field.TypeBool, Default: false},
		{Name: "customer_id", Type: field.TypeInt},
	}
	// CustomerAddressesTable holds the schema information for the "customer_addresses" table.
	CustomerAddressesTable = &schema.Table{
		Name:       "customer_addresses",
		Columns:    CustomerAddressesColumns,
		PrimaryKey: []*schema.Column{CustomerAddressesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "customer_addresses_customers_addresses",
				Columns:    []*schema.Column{CustomerAddressesColumns[20]},
				RefColumns: []*schema.Column{CustomersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "customeraddress_customer_id",
				Unique:  false,
				Columns: []*schema.Column{CustomerAddressesColumns[20]},
			},
		},
	}
	// CustomerGroupsColumns holds the columns for the "customer_groups" table.
	CustomerGroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "customer_groups", Type: field.TypeInt, Nullable: true},
	}
	// CustomerGroupsTable holds the schema information for the "customer_groups" table.
	CustomerGroupsTable = &schema.Table{
		Name:       "customer_groups",
		Columns:    CustomerGroupsColumns,
		PrimaryKey: []*schema.Column{CustomerGroupsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "customer_groups_customers_groups",
				Columns:    []*schema.Column{CustomerGroupsColumns[10]},
				RefColumns: []*schema.Column{CustomersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// EmailTemplatesColumns holds the columns for the "email_templates" table.
	EmailTemplatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "code", Type: field.TypeString, Unique: true},
		{Name: "variables", Type: field.TypeJSON, Nullable: true},
	}
	// EmailTemplatesTable holds the schema information for the "email_templates" table.
	EmailTemplatesTable = &schema.Table{
		Name:       "email_templates",
		Columns:    EmailTemplatesColumns,
		PrimaryKey: []*schema.Column{EmailTemplatesColumns[0]},
	}
	// EmailTemplateTranslationsColumns holds the columns for the "email_template_translations" table.
	EmailTemplateTranslationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "locale", Type: field.TypeString, Size: 8},
		{Name: "subject", Type: field.TypeString},
		{Name: "body_html", Type: field.TypeString, Size: 2147483647},
		{Name: "email_template_id", Type: field.TypeInt},
	}
	// EmailTemplateTranslationsTable holds the schema information for the "email_template_translations" table.
	EmailTemplateTranslationsTable = &schema.Table{
		Name:       "email_template_translations",
		Columns:    EmailTemplateTranslationsColumns,
		PrimaryKey: []*schema.Column{EmailTemplateTranslationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "email_template_translations_email_templates_translations",
				Columns:    []*schema.Column{EmailTemplateTranslationsColumns[11]},
				RefColumns: []*schema.Column{EmailTemplatesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "emailtemplatetranslation_email_template_id_locale",
				Unique:  true,
				Columns: []*schema.Column{EmailTemplateTranslationsColumns[11], EmailTemplateTranslationsColumns[8]},
			},
		},
	}
	// FormDefinitionsColumns holds the columns for the "form_definitions" table.
	FormDefinitionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "fields", Type: field.TypeJSON, Nullable: true},
		{Name: "notify_emails", Type: field.TypeJSON, Nullable: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// FormDefinitionsTable holds the schema information for the "form_definitions" table.
	FormDefinitionsTable = &schema.Table{
		Name:       "form_definitions",
		Columns:    FormDefinitionsColumns,
		PrimaryKey: []*schema.Column{FormDefinitionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "formdefinition_is_active",
				Unique:  false,
				Columns: []*schema.Column{FormDefinitionsColumns[11]},
			},
		},
	}
	// FormDefinitionTranslationsColumns holds the columns for the "form_definition_translations" table.
	FormDefinitionTranslationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "locale", Type: field.TypeString, Size: 8},
		{Name: "title", Type: field.TypeString},
		{Name: "field_labels", Type: field.TypeJSON, Nullable: true},
		{Name: "form_definition_id", Type: field.TypeInt},
	}
	// FormDefinitionTranslationsTable holds the schema information for the "form_definition_translations" table.
	FormDefinitionTranslationsTable = &schema.Table{
		Name:       "form_definition_translations",
		Columns:    FormDefinitionTranslationsColumns,
		PrimaryKey: []*schema.Column{FormDefinitionTranslationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "form_definition_translations_form_definitions_translations",
				Columns:    []*schema.Column{FormDefinitionTranslationsColumns[11]},
				RefColumns: []*schema.Column{FormDefinitionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "formdefinitiontranslation_form_definition_id_locale",
				Unique:  true,
				Columns: []*schema.Column{FormDefinitionTranslationsColumns[11], FormDefinitionTranslationsColumns[8]},
			},
		},
	}
	// InquiriesColumns holds the columns for the "inquiries" table.
	InquiriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "customer_id", Type: field.TypeInt, Nullable: true},
		{Name: "email", Type: field.TypeString},
		{Name: "phone", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "company", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "payload", Type: field.TypeJSON, Nullable: true},
		{Name: "product_id", Type: field.TypeInt, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"new", "contacted", "qualified", "converted", "closed"}, Default: "new"},
		{Name: "assigned_admin_id", Type: field.TypeInt, Nullable: true},
		{Name: "converted_order_id", Type: field.TypeInt, Nullable: true},
		{Name: "form_id", Type: field.TypeInt},
	}
	// InquiriesTable holds the schema information for the "inquiries" table.
	InquiriesTable = &schema.Table{
		Name:       "inquiries",
		Columns:    InquiriesColumns,
		PrimaryKey: []*schema.Column{InquiriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "inquiries_form_definitions_inquiries",
				Columns:    []*schema.Column{InquiriesColumns[18]},
				RefColumns: []*schema.Column{FormDefinitionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "inquiry_status",
				Unique:  false,
				Columns: []*schema.Column{InquiriesColumns[15]},
			},
			{
				Name:    "inquiry_form_id",
				Unique:  false,
				Columns: []*schema.Column{InquiriesColumns[18]},
			},
			{
				Name:    "inquiry_customer_id",
				Unique:  false,
				Columns: []*schema.Column{InquiriesColumns[8]},
			},
		},
	}
	// LocalesColumns holds the columns for the "locales" table.
	LocalesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 8},
		{Name: "name", Type: field.TypeString},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// LocalesTable holds the schema information for the "locales" table.
	LocalesTable = &schema.Table{
		Name:       "locales",
		Columns:    LocalesColumns,
		PrimaryKey: []*schema.Column{LocalesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "locale_is_active",
				Unique:  false,
				Columns: []*schema.Column{LocalesColumns[10]},
			},
		},
	}
	// MediaColumns holds the columns for the "media" table.
	MediaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "key", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "mime_type", Type: field.TypeString},
		{Name: "size_bytes", Type: field.TypeInt64},
		{Name: "width", Type: field.TypeInt, Nullable: true},
		{Name: "height", Type: field.TypeInt, Nullable: true},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"image", "document", "video"}, Default: "image"},
	}
	// MediaTable holds the schema information for the "media" table.
	MediaTable = &schema.Table{
		Name:       "media",
		Columns:    MediaColumns,
		PrimaryKey: []*schema.Column{MediaColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "media_kind",
				Unique:  false,
				Columns: []*schema.Column{MediaColumns[14]},
			},
		},
	}
	// MediaTranslationsColumns holds the columns for the "media_translations" table.
	MediaTranslationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "locale", Type: field.TypeString, Size: 8},
		{Name: "alt", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "media_id", Type: field.TypeInt},
	}
	// MediaTranslationsTable holds the schema information for the "media_translations" table.
	MediaTranslationsTable = &schema.Table{
		Name:       "media_translations",
		Columns:    MediaTranslationsColumns,
		PrimaryKey: []*schema.Column{MediaTranslationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "media_translations_media_translations",
				Columns:    []*schema.Column{MediaTranslationsColumns[10]},
				RefColumns: []*schema.Column{MediaColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "mediatranslation_media_id_locale",
				Unique:  true,
				Columns: []*schema.Column{MediaTranslationsColumns[10], MediaTranslationsColumns[8]},
			},
		},
	}
	// MenusColumns holds the columns for the "menus" table.
	MenusColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "location", Type: field.TypeString, Default: "header"},
	}
	// MenusTable holds the schema information for the "menus" table.
	MenusTable = &schema.Table{
		Name:       "menus",
		Columns:    MenusColumns,
		PrimaryKey: []*schema.Column{MenusColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "menu_location",
				Unique:  false,
				Columns: []*schema.Column{MenusColumns[9]},
			},
		},
	}
	// MenuItemsColumns holds the columns for the "menu_items" table.
	MenuItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "parent_id", Type: field.TypeInt, Nullable: true},
		{Name: "target_type", Type: field.TypeEnum, Enums: []string{"page", "category", "url", "post"}, Default: "url"},
		{Name: "target_id", Type: field.TypeInt, Nullable: true},
		{Name: "url", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "position", Type: field.TypeInt, Default: 0},
		{Name: "menu_id", Type: field.TypeInt},
	}
	// MenuItemsTable holds the schema information for the "menu_items" table.
	MenuItemsTable = &schema.Table{
		Name:       "menu_items",
		Columns:    MenuItemsColumns,
		PrimaryKey: []*schema.Column{MenuItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "menu_items_menus_items",
				Columns:    []*schema.Column{MenuItemsColumns[13]},
				RefColumns: []*schema.Column{MenusColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "menuitem_menu_id",
				Unique:  false,
				Columns: []*schema.Column{MenuItemsColumns[13]},
			},
			{
				Name:    "menuitem_parent_id",
				Unique:  false,
				Columns: []*schema.Column{MenuItemsColumns[8]},
			},
		},
	}
	// MenuItemTranslationsColumns holds the columns for the "menu_item_translations" table.
	MenuItemTranslationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "locale", Type: field.TypeString, Size: 8},
		{Name: "title", Type: field.TypeString},
		{Name: "menu_item_id", Type: field.TypeInt},
	}
	// MenuItemTranslationsTable holds the schema information for the "menu_item_translations" table.
	MenuItemTranslationsTable = &schema.Table{
		Name:       "menu_item_translations",
		Columns:    MenuItemTranslationsColumns,
		PrimaryKey: []*schema.Column{MenuItemTranslationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "menu_item_translations_menu_items_translations",
				Columns:    []*schema.Column{MenuItemTranslationsColumns[10]},
				RefColumns: []*schema.Column{MenuItemsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "menuitemtranslation_menu_item_id_locale",
				Unique:  true,
				Columns: []*schema.Column{MenuItemTranslationsColumns[10], MenuItemTranslationsColumns[8]},
			},
		},
	}
	// NotificationsColumns holds the columns for the "notifications" table.
	NotificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "channel", Type: field.TypeEnum, Enums: []string{"email", "webhook", "inapp"}, Default: "email"},
		{Name: "recipient", Type: field.TypeString},
		{Name: "template_code", Type: field.TypeString, Default: ""},
		{Name: "payload", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "sent", "failed"}, Default: "pending"},
		{Name: "attempts", Type: field.TypeInt, Default: 0},
		{Name: "sent_at", Type: field.TypeTime, Nullable: true},
	}
	// NotificationsTable holds the schema information for the "notifications" table.
	NotificationsTable = &schema.Table{
		Name:       "notifications",
		Columns:    NotificationsColumns,
		PrimaryKey: []*schema.Column{NotificationsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "notification_status",
				Unique:  false,
				Columns: []*schema.Column{NotificationsColumns[12]},
			},
			{
				Name:    "notification_template_code",
				Unique:  false,
				Columns: []*schema.Column{NotificationsColumns[10]},
			},
		},
	}
	// PagesColumns holds the columns for the "pages" table.
	PagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"draft", "published", "archived"}, Default: "draft"},
		{Name: "template", Type: field.TypeString, Default: "default"},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
	}
	// PagesTable holds the schema information for the "pages" table.
	PagesTable = &schema.Table{
		Name:       "pages",
		Columns:    PagesColumns,
		PrimaryKey: []*schema.Column{PagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "page_status",
				Unique:  false,
				Columns: []*schema.Column{PagesColumns[9]},
			},
		},
	}
	// PageTranslationsColumns holds the columns for the "page_translations" table.
	PageTranslationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "locale", Type: field.TypeString, Size: 8},
		{Name: "title", Type: field.TypeString},
		{Name: "content", Type: field.TypeJSON, Nullable: true},
		{Name: "seo_title", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "seo_desc", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "page_id", Type: field.TypeInt},
	}
	// PageTranslationsTable holds the schema information for the "page_translations" table.
	PageTranslationsTable = &schema.Table{
		Name:       "page_translations",
		Columns:    PageTranslationsColumns,
		PrimaryKey: []*schema.Column{PageTranslationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "page_translations_pages_translations",
				Columns:    []*schema.Column{PageTranslationsColumns[13]},
				RefColumns: []*schema.Column{PagesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "pagetranslation_page_id_locale",
				Unique:  true,
				Columns: []*schema.Column{PageTranslationsColumns[13], PageTranslationsColumns[8]},
			},
		},
	}
	// PermissionsColumns holds the columns for the "permissions" table.
	PermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "resource", Type: field.TypeString},
		{Name: "action", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Default: ""},
	}
	// PermissionsTable holds the schema information for the "permissions" table.
	PermissionsTable = &schema.Table{
		Name:       "permissions",
		Columns:    PermissionsColumns,
		PrimaryKey: []*schema.Column{PermissionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "permission_resource_action",
				Unique:  true,
				Columns: []*schema.Column{PermissionsColumns[8], PermissionsColumns[9]},
			},
		},
	}
	// ProductsColumns holds the columns for the "products" table.
	ProductsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "product_type", Type: field.TypeEnum, Enums: []string{"simple", "variable", "virtual", "grouped"}, Default: "simple"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"draft", "published", "archived"}, Default: "draft"},
		{Name: "category_id", Type: field.TypeInt, Nullable: true},
		{Name: "weight_g", Type: field.TypeInt, Nullable: true},
		{Name: "is_virtual", Type: field.TypeBool, Default: false},
		{Name: "is_downloadable", Type: field.TypeBool, Default: false},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
		{Name: "collection_products", Type: field.TypeInt, Nullable: true},
		{Name: "tag_products", Type: field.TypeInt, Nullable: true},
	}
	// ProductsTable holds the schema information for the "products" table.
	ProductsTable = &schema.Table{
		Name:       "products",
		Columns:    ProductsColumns,
		PrimaryKey: []*schema.Column{ProductsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "products_collections_products",
				Columns:    []*schema.Column{ProductsColumns[16]},
				RefColumns: []*schema.Column{CollectionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "products_tags_products",
				Columns:    []*schema.Column{ProductsColumns[17]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "product_status",
				Unique:  false,
				Columns: []*schema.Column{ProductsColumns[10]},
			},
			{
				Name:    "product_product_type",
				Unique:  false,
				Columns: []*schema.Column{ProductsColumns[9]},
			},
			{
				Name:    "product_category_id",
				Unique:  false,
				Columns: []*schema.Column{ProductsColumns[11]},
			},
		},
	}
	// ProductMediaColumns holds the columns for the "product_media" table.
	ProductMediaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "product_id", Type: field.TypeInt},
		{Name: "media_id", Type: field.TypeInt},
		{Name: "position", Type: field.TypeInt, Default: 0},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"image", "gallery", "document"}, Default: "gallery"},
	}
	// ProductMediaTable holds the schema information for the "product_media" table.
	ProductMediaTable = &schema.Table{
		Name:       "product_media",
		Columns:    ProductMediaColumns,
		PrimaryKey: []*schema.Column{ProductMediaColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "productmedia_product_id",
				Unique:  false,
				Columns: []*schema.Column{ProductMediaColumns[8]},
			},
			{
				Name:    "productmedia_media_id",
				Unique:  false,
				Columns: []*schema.Column{ProductMediaColumns[9]},
			},
		},
	}
	// ProductOptionsColumns holds the columns for the "product_options" table.
	ProductOptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "position", Type: field.TypeInt, Default: 0},
		{Name: "product_id", Type: field.TypeInt},
	}
	// ProductOptionsTable holds the schema information for the "product_options" table.
	ProductOptionsTable = &schema.Table{
		Name:       "product_options",
		Columns:    ProductOptionsColumns,
		PrimaryKey: []*schema.Column{ProductOptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "product_options_products_options",
				Columns:    []*schema.Column{ProductOptionsColumns[10]},
				RefColumns: []*schema.Column{ProductsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "productoption_product_id",
				Unique:  false,
				Columns: []*schema.Column{ProductOptionsColumns[10]},
			},
		},
	}
	// ProductOptionValuesColumns holds the columns for the "product_option_values" table.
	ProductOptionValuesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "value", Type: field.TypeString},
		{Name: "position", Type: field.TypeInt, Default: 0},
		{Name: "option_id", Type: field.TypeInt},
	}
	// ProductOptionValuesTable holds the schema information for the "product_option_values" table.
	ProductOptionValuesTable = &schema.Table{
		Name:       "product_option_values",
		Columns:    ProductOptionValuesColumns,
		PrimaryKey: []*schema.Column{ProductOptionValuesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "product_option_values_product_options_values",
				Columns:    []*schema.Column{ProductOptionValuesColumns[10]},
				RefColumns: []*schema.Column{ProductOptionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "productoptionvalue_option_id",
				Unique:  false,
				Columns: []*schema.Column{ProductOptionValuesColumns[10]},
			},
		},
	}
	// ProductTranslationsColumns holds the columns for the "product_translations" table.
	ProductTranslationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "locale", Type: field.TypeString, Size: 8},
		{Name: "title", Type: field.TypeString},
		{Name: "subtitle", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "material", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "origin", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "packing", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "seo_title", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "seo_desc", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "product_id", Type: field.TypeInt},
	}
	// ProductTranslationsTable holds the schema information for the "product_translations" table.
	ProductTranslationsTable = &schema.Table{
		Name:       "product_translations",
		Columns:    ProductTranslationsColumns,
		PrimaryKey: []*schema.Column{ProductTranslationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "product_translations_products_translations",
				Columns:    []*schema.Column{ProductTranslationsColumns[17]},
				RefColumns: []*schema.Column{ProductsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "producttranslation_product_id_locale",
				Unique:  true,
				Columns: []*schema.Column{ProductTranslationsColumns[17], ProductTranslationsColumns[8]},
			},
		},
	}
	// RegionsColumns holds the columns for the "regions" table.
	RegionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "locale", Type: field.TypeString, Size: 8},
		{Name: "currency_code", Type: field.TypeString, Size: 3},
		{Name: "tax_inclusive", Type: field.TypeBool, Default: false},
		{Name: "countries", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive"}, Default: "active"},
	}
	// RegionsTable holds the schema information for the "regions" table.
	RegionsTable = &schema.Table{
		Name:       "regions",
		Columns:    RegionsColumns,
		PrimaryKey: []*schema.Column{RegionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "region_status",
				Unique:  false,
				Columns: []*schema.Column{RegionsColumns[13]},
			},
		},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "is_system", Type: field.TypeBool, Default: false},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "role_is_system",
				Unique:  false,
				Columns: []*schema.Column{RolesColumns[11]},
			},
		},
	}
	// StoresColumns holds the columns for the "stores" table.
	StoresColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "site_type", Type: field.TypeEnum, Enums: []string{"corporate", "store", "hybrid"}, Default: "store"},
		{Name: "default_locale", Type: field.TypeString, Size: 8, Default: "en"},
		{Name: "default_currency", Type: field.TypeString, Size: 3, Default: "USD"},
		{Name: "feature_flags", Type: field.TypeJSON, Nullable: true},
		{Name: "timezone", Type: field.TypeString, Default: "UTC"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "maintenance"}, Default: "active"},
	}
	// StoresTable holds the schema information for the "stores" table.
	StoresTable = &schema.Table{
		Name:       "stores",
		Columns:    StoresColumns,
		PrimaryKey: []*schema.Column{StoresColumns[0]},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "slug", Type: field.TypeString, Unique: true},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
	}
	// TagTranslationsColumns holds the columns for the "tag_translations" table.
	TagTranslationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "locale", Type: field.TypeString, Size: 8},
		{Name: "name", Type: field.TypeString},
		{Name: "tag_id", Type: field.TypeInt},
	}
	// TagTranslationsTable holds the schema information for the "tag_translations" table.
	TagTranslationsTable = &schema.Table{
		Name:       "tag_translations",
		Columns:    TagTranslationsColumns,
		PrimaryKey: []*schema.Column{TagTranslationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tag_translations_tags_translations",
				Columns:    []*schema.Column{TagTranslationsColumns[10]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tagtranslation_tag_id_locale",
				Unique:  true,
				Columns: []*schema.Column{TagTranslationsColumns[10], TagTranslationsColumns[8]},
			},
		},
	}
	// TaxRatesColumns holds the columns for the "tax_rates" table.
	TaxRatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "country_code", Type: field.TypeString, Nullable: true, Size: 2},
		{Name: "rate", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric(5,4)"}},
		{Name: "name", Type: field.TypeString},
		{Name: "priority", Type: field.TypeInt, Default: 0},
		{Name: "region_id", Type: field.TypeInt},
	}
	// TaxRatesTable holds the schema information for the "tax_rates" table.
	TaxRatesTable = &schema.Table{
		Name:       "tax_rates",
		Columns:    TaxRatesColumns,
		PrimaryKey: []*schema.Column{TaxRatesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tax_rates_regions_tax_rates",
				Columns:    []*schema.Column{TaxRatesColumns[12]},
				RefColumns: []*schema.Column{RegionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "taxrate_region_id",
				Unique:  false,
				Columns: []*schema.Column{TaxRatesColumns[12]},
			},
			{
				Name:    "taxrate_country_code",
				Unique:  false,
				Columns: []*schema.Column{TaxRatesColumns[8]},
			},
		},
	}
	// VariantsColumns holds the columns for the "variants" table.
	VariantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "sku", Type: field.TypeString, Unique: true},
		{Name: "barcode", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "weight_g", Type: field.TypeInt, Nullable: true},
		{Name: "allow_backorder", Type: field.TypeBool, Default: false},
		{Name: "inventory", Type: field.TypeInt, Default: 0},
		{Name: "position", Type: field.TypeInt, Default: 0},
		{Name: "product_id", Type: field.TypeInt},
	}
	// VariantsTable holds the schema information for the "variants" table.
	VariantsTable = &schema.Table{
		Name:       "variants",
		Columns:    VariantsColumns,
		PrimaryKey: []*schema.Column{VariantsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "variants_products_variants",
				Columns:    []*schema.Column{VariantsColumns[14]},
				RefColumns: []*schema.Column{ProductsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "variant_product_id",
				Unique:  false,
				Columns: []*schema.Column{VariantsColumns[14]},
			},
			{
				Name:    "variant_sku",
				Unique:  false,
				Columns: []*schema.Column{VariantsColumns[8]},
			},
		},
	}
	// VariantOptionValuesColumns holds the columns for the "variant_option_values" table.
	VariantOptionValuesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "option_value_id", Type: field.TypeInt},
		{Name: "variant_id", Type: field.TypeInt},
	}
	// VariantOptionValuesTable holds the schema information for the "variant_option_values" table.
	VariantOptionValuesTable = &schema.Table{
		Name:       "variant_option_values",
		Columns:    VariantOptionValuesColumns,
		PrimaryKey: []*schema.Column{VariantOptionValuesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "variant_option_values_variants_option_values",
				Columns:    []*schema.Column{VariantOptionValuesColumns[9]},
				RefColumns: []*schema.Column{VariantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "variantoptionvalue_variant_id_option_value_id",
				Unique:  true,
				Columns: []*schema.Column{VariantOptionValuesColumns[9], VariantOptionValuesColumns[8]},
			},
		},
	}
	// VariantPricesColumns holds the columns for the "variant_prices" table.
	VariantPricesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "currency_code", Type: field.TypeString, Size: 3},
		{Name: "amount", Type: field.TypeInt64},
		{Name: "compare_at_amount", Type: field.TypeInt64, Nullable: true},
		{Name: "variant_id", Type: field.TypeInt},
	}
	// VariantPricesTable holds the schema information for the "variant_prices" table.
	VariantPricesTable = &schema.Table{
		Name:       "variant_prices",
		Columns:    VariantPricesColumns,
		PrimaryKey: []*schema.Column{VariantPricesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "variant_prices_variants_prices",
				Columns:    []*schema.Column{VariantPricesColumns[11]},
				RefColumns: []*schema.Column{VariantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "variantprice_variant_id_currency_code",
				Unique:  true,
				Columns: []*schema.Column{VariantPricesColumns[11], VariantPricesColumns[8]},
			},
		},
	}
	// RoleAdminsColumns holds the columns for the "role_admins" table.
	RoleAdminsColumns = []*schema.Column{
		{Name: "role_id", Type: field.TypeInt},
		{Name: "admin_user_id", Type: field.TypeInt},
	}
	// RoleAdminsTable holds the schema information for the "role_admins" table.
	RoleAdminsTable = &schema.Table{
		Name:       "role_admins",
		Columns:    RoleAdminsColumns,
		PrimaryKey: []*schema.Column{RoleAdminsColumns[0], RoleAdminsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "role_admins_role_id",
				Columns:    []*schema.Column{RoleAdminsColumns[0]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "role_admins_admin_user_id",
				Columns:    []*schema.Column{RoleAdminsColumns[1]},
				RefColumns: []*schema.Column{AdminUsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// RolePermissionsColumns holds the columns for the "role_permissions" table.
	RolePermissionsColumns = []*schema.Column{
		{Name: "role_id", Type: field.TypeInt},
		{Name: "permission_id", Type: field.TypeInt},
	}
	// RolePermissionsTable holds the schema information for the "role_permissions" table.
	RolePermissionsTable = &schema.Table{
		Name:       "role_permissions",
		Columns:    RolePermissionsColumns,
		PrimaryKey: []*schema.Column{RolePermissionsColumns[0], RolePermissionsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "role_permissions_role_id",
				Columns:    []*schema.Column{RolePermissionsColumns[0]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "role_permissions_permission_id",
				Columns:    []*schema.Column{RolePermissionsColumns[1]},
				RefColumns: []*schema.Column{PermissionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AdminUsersTable,
		BlogPostsTable,
		BlogPostTranslationsTable,
		CategoriesTable,
		CategoryTranslationsTable,
		CollectionsTable,
		CollectionTranslationsTable,
		CurrenciesTable,
		CustomersTable,
		CustomerAddressesTable,
		CustomerGroupsTable,
		EmailTemplatesTable,
		EmailTemplateTranslationsTable,
		FormDefinitionsTable,
		FormDefinitionTranslationsTable,
		InquiriesTable,
		LocalesTable,
		MediaTable,
		MediaTranslationsTable,
		MenusTable,
		MenuItemsTable,
		MenuItemTranslationsTable,
		NotificationsTable,
		PagesTable,
		PageTranslationsTable,
		PermissionsTable,
		ProductsTable,
		ProductMediaTable,
		ProductOptionsTable,
		ProductOptionValuesTable,
		ProductTranslationsTable,
		RegionsTable,
		RolesTable,
		StoresTable,
		TagsTable,
		TagTranslationsTable,
		TaxRatesTable,
		VariantsTable,
		VariantOptionValuesTable,
		VariantPricesTable,
		RoleAdminsTable,
		RolePermissionsTable,
	}
)

func init() {
	BlogPostTranslationsTable.ForeignKeys[0].RefTable = BlogPostsTable
	CategoryTranslationsTable.ForeignKeys[0].RefTable = CategoriesTable
	CollectionTranslationsTable.ForeignKeys[0].RefTable = CollectionsTable
	CustomerAddressesTable.ForeignKeys[0].RefTable = CustomersTable
	CustomerGroupsTable.ForeignKeys[0].RefTable = CustomersTable
	EmailTemplateTranslationsTable.ForeignKeys[0].RefTable = EmailTemplatesTable
	FormDefinitionTranslationsTable.ForeignKeys[0].RefTable = FormDefinitionsTable
	InquiriesTable.ForeignKeys[0].RefTable = FormDefinitionsTable
	MediaTranslationsTable.ForeignKeys[0].RefTable = MediaTable
	MenuItemsTable.ForeignKeys[0].RefTable = MenusTable
	MenuItemTranslationsTable.ForeignKeys[0].RefTable = MenuItemsTable
	PageTranslationsTable.ForeignKeys[0].RefTable = PagesTable
	ProductsTable.ForeignKeys[0].RefTable = CollectionsTable
	ProductsTable.ForeignKeys[1].RefTable = TagsTable
	ProductOptionsTable.ForeignKeys[0].RefTable = ProductsTable
	ProductOptionValuesTable.ForeignKeys[0].RefTable = ProductOptionsTable
	ProductTranslationsTable.ForeignKeys[0].RefTable = ProductsTable
	TagTranslationsTable.ForeignKeys[0].RefTable = TagsTable
	TaxRatesTable.ForeignKeys[0].RefTable = RegionsTable
	VariantsTable.ForeignKeys[0].RefTable = ProductsTable
	VariantOptionValuesTable.ForeignKeys[0].RefTable = VariantsTable
	VariantPricesTable.ForeignKeys[0].RefTable = VariantsTable
	RoleAdminsTable.ForeignKeys[0].RefTable = RolesTable
	RoleAdminsTable.ForeignKeys[1].RefTable = AdminUsersTable
	RolePermissionsTable.ForeignKeys[0].RefTable = RolesTable
	RolePermissionsTable.ForeignKeys[1].RefTable = PermissionsTable
}
