// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/blogpost"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/blogposttranslation"
)

// BlogPostTranslationCreate is the builder for creating a BlogPostTranslation entity.
type BlogPostTranslationCreate struct {
	config
	mutation *BlogPostTranslationMutation
	hooks    []Hook
}

// SetCreatedBy sets the "created_by" field.
func (_c *BlogPostTranslationCreate) SetCreatedBy(v int64) *BlogPostTranslationCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *BlogPostTranslationCreate) SetNillableCreatedBy(v *int64) *BlogPostTranslationCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *BlogPostTranslationCreate) SetUpdatedBy(v int64) *BlogPostTranslationCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *BlogPostTranslationCreate) SetNillableUpdatedBy(v *int64) *BlogPostTranslationCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *BlogPostTranslationCreate) SetTenantID(v int64) *BlogPostTranslationCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *BlogPostTranslationCreate) SetNillableTenantID(v *int64) *BlogPostTranslationCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *BlogPostTranslationCreate) SetVersion(v int) *BlogPostTranslationCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *BlogPostTranslationCreate) SetNillableVersion(v *int) *BlogPostTranslationCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BlogPostTranslationCreate) SetCreatedAt(v time.Time) *BlogPostTranslationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BlogPostTranslationCreate) SetNillableCreatedAt(v *time.Time) *BlogPostTranslationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BlogPostTranslationCreate) SetUpdatedAt(v time.Time) *BlogPostTranslationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BlogPostTranslationCreate) SetNillableUpdatedAt(v *time.Time) *BlogPostTranslationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *BlogPostTranslationCreate) SetDeletedAt(v time.Time) *BlogPostTranslationCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *BlogPostTranslationCreate) SetNillableDeletedAt(v *time.Time) *BlogPostTranslationCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetBlogPostID sets the "blog_post_id" field.
func (_c *BlogPostTranslationCreate) SetBlogPostID(v int) *BlogPostTranslationCreate {
	_c.mutation.SetBlogPostID(v)
	return _c
}

// SetLocale sets the "locale" field.
func (_c *BlogPostTranslationCreate) SetLocale(v string) *BlogPostTranslationCreate {
	_c.mutation.SetLocale(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *BlogPostTranslationCreate) SetTitle(v string) *BlogPostTranslationCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetExcerpt sets the "excerpt" field.
func (_c *BlogPostTranslationCreate) SetExcerpt(v string) *BlogPostTranslationCreate {
	_c.mutation.SetExcerpt(v)
	return _c
}

// SetNillableExcerpt sets the "excerpt" field if the given value is not nil.
func (_c *BlogPostTranslationCreate) SetNillableExcerpt(v *string) *BlogPostTranslationCreate {
	if v != nil {
		_c.SetExcerpt(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *BlogPostTranslationCreate) SetContent(v string) *BlogPostTranslationCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *BlogPostTranslationCreate) SetNillableContent(v *string) *BlogPostTranslationCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetSeoTitle sets the "seo_title" field.
func (_c *BlogPostTranslationCreate) SetSeoTitle(v string) *BlogPostTranslationCreate {
	_c.mutation.SetSeoTitle(v)
	return _c
}

// SetNillableSeoTitle sets the "seo_title" field if the given value is not nil.
func (_c *BlogPostTranslationCreate) SetNillableSeoTitle(v *string) *BlogPostTranslationCreate {
	if v != nil {
		_c.SetSeoTitle(*v)
	}
	return _c
}

// SetSeoDesc sets the "seo_desc" field.
func (_c *BlogPostTranslationCreate) SetSeoDesc(v string) *BlogPostTranslationCreate {
	_c.mutation.SetSeoDesc(v)
	return _c
}

// SetNillableSeoDesc sets the "seo_desc" field if the given value is not nil.
func (_c *BlogPostTranslationCreate) SetNillableSeoDesc(v *string) *BlogPostTranslationCreate {
	if v != nil {
		_c.SetSeoDesc(*v)
	}
	return _c
}

// SetBlogPost sets the "blog_post" edge to the BlogPost entity.
func (_c *BlogPostTranslationCreate) SetBlogPost(v *BlogPost) *BlogPostTranslationCreate {
	return _c.SetBlogPostID(v.ID)
}

// Mutation returns the BlogPostTranslationMutation object of the builder.
func (_c *BlogPostTranslationCreate) Mutation() *BlogPostTranslationMutation {
	return _c.mutation
}

// Save creates the BlogPostTranslation in the database.
func (_c *BlogPostTranslationCreate) Save(ctx context.Context) (*BlogPostTranslation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BlogPostTranslationCreate) SaveX(ctx context.Context) *BlogPostTranslation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BlogPostTranslationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BlogPostTranslationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BlogPostTranslationCreate) defaults() {
	if _, ok := _c.mutation.Version(); !ok {
		v := blogposttranslation.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := blogposttranslation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := blogposttranslation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Excerpt(); !ok {
		v := blogposttranslation.DefaultExcerpt
		_c.mutation.SetExcerpt(v)
	}
	if _, ok := _c.mutation.Content(); !ok {
		v := blogposttranslation.DefaultContent
		_c.mutation.SetContent(v)
	}
	if _, ok := _c.mutation.SeoTitle(); !ok {
		v := blogposttranslation.DefaultSeoTitle
		_c.mutation.SetSeoTitle(v)
	}
	if _, ok := _c.mutation.SeoDesc(); !ok {
		v := blogposttranslation.DefaultSeoDesc
		_c.mutation.SetSeoDesc(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BlogPostTranslationCreate) check() error {
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "BlogPostTranslation.version"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BlogPostTranslation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BlogPostTranslation.updated_at"`)}
	}
	if _, ok := _c.mutation.BlogPostID(); !ok {
		return &ValidationError{Name: "blog_post_id", err: errors.New(`ent: missing required field "BlogPostTranslation.blog_post_id"`)}
	}
	if _, ok := _c.mutation.Locale(); !ok {
		return &ValidationError{Name: "locale", err: errors.New(`ent: missing required field "BlogPostTranslation.locale"`)}
	}
	if v, ok := _c.mutation.Locale(); ok {
		if err := blogposttranslation.LocaleValidator(v); err != nil {
			return &ValidationError{Name: "locale", err: fmt.Errorf(`ent: validator failed for field "BlogPostTranslation.locale": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "BlogPostTranslation.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := blogposttranslation.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "BlogPostTranslation.title": %w`, err)}
		}
	}
	if len(_c.mutation.BlogPostIDs()) == 0 {
		return &ValidationError{Name: "blog_post", err: errors.New(`ent: missing required edge "BlogPostTranslation.blog_post"`)}
	}
	return nil
}

func (_c *BlogPostTranslationCreate) sqlSave(ctx context.Context) (*BlogPostTranslation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BlogPostTranslationCreate) createSpec() (*BlogPostTranslation, *sqlgraph.CreateSpec) {
	var (
		_node = &BlogPostTranslation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(blogposttranslation.Table, sqlgraph.NewFieldSpec(blogposttranslation.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(blogposttranslation.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(blogposttranslation.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(blogposttranslation.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(blogposttranslation.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(blogposttranslation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(blogposttranslation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(blogposttranslation.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Locale(); ok {
		_spec.SetField(blogposttranslation.FieldLocale, field.TypeString, value)
		_node.Locale = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(blogposttranslation.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Excerpt(); ok {
		_spec.SetField(blogposttranslation.FieldExcerpt, field.TypeString, value)
		_node.Excerpt = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(blogposttranslation.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.SeoTitle(); ok {
		_spec.SetField(blogposttranslation.FieldSeoTitle, field.TypeString, value)
		_node.SeoTitle = value
	}
	if value, ok := _c.mutation.SeoDesc(); ok {
		_spec.SetField(blogposttranslation.FieldSeoDesc, field.TypeString, value)
		_node.SeoDesc = value
	}
	if nodes := _c.mutation.BlogPostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   blogposttranslation.BlogPostTable,
			Columns: []string{blogposttranslation.BlogPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blogpost.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BlogPostID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BlogPostTranslationCreateBulk is the builder for creating many BlogPostTranslation entities in bulk.
type BlogPostTranslationCreateBulk struct {
	config
	err      error
	builders []*BlogPostTranslationCreate
}

// Save creates the BlogPostTranslation entities in the database.
func (_c *BlogPostTranslationCreateBulk) Save(ctx context.Context) ([]*BlogPostTranslation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BlogPostTranslation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BlogPostTranslationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BlogPostTranslationCreateBulk) SaveX(ctx context.Context) []*BlogPostTranslation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BlogPostTranslationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BlogPostTranslationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
