// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/discount"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/discountcondition"
)

// DiscountCondition is the model entity for the DiscountCondition schema.
type DiscountCondition struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int64 `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy int64 `json:"updated_by,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID int64 `json:"tenant_id,omitempty"`
	// Version holds the value of the "version" field.
	Version int `json:"version,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// DiscountID holds the value of the "discount_id" field.
	DiscountID int `json:"discount_id,omitempty"`
	// Type holds the value of the "type" field.
	Type discountcondition.Type `json:"type,omitempty"`
	// Values holds the value of the "values" field.
	Values []int `json:"values,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DiscountConditionQuery when eager-loading is set.
	Edges        DiscountConditionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DiscountConditionEdges holds the relations/edges for other nodes in the graph.
type DiscountConditionEdges struct {
	// Discount holds the value of the discount edge.
	Discount *Discount `json:"discount,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DiscountOrErr returns the Discount value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DiscountConditionEdges) DiscountOrErr() (*Discount, error) {
	if e.Discount != nil {
		return e.Discount, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: discount.Label}
	}
	return nil, &NotLoadedError{edge: "discount"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DiscountCondition) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case discountcondition.FieldValues:
			values[i] = new([]byte)
		case discountcondition.FieldID, discountcondition.FieldCreatedBy, discountcondition.FieldUpdatedBy, discountcondition.FieldTenantID, discountcondition.FieldVersion, discountcondition.FieldDiscountID:
			values[i] = new(sql.NullInt64)
		case discountcondition.FieldType:
			values[i] = new(sql.NullString)
		case discountcondition.FieldCreatedAt, discountcondition.FieldUpdatedAt, discountcondition.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DiscountCondition fields.
func (_m *DiscountCondition) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case discountcondition.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case discountcondition.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.Int64
			}
		case discountcondition.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.Int64
			}
		case discountcondition.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.Int64
			}
		case discountcondition.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		case discountcondition.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case discountcondition.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case discountcondition.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case discountcondition.FieldDiscountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field discount_id", values[i])
			} else if value.Valid {
				_m.DiscountID = int(value.Int64)
			}
		case discountcondition.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = discountcondition.Type(value.String)
			}
		case discountcondition.FieldValues:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field values", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Values); err != nil {
					return fmt.Errorf("unmarshal field values: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DiscountCondition.
// This includes values selected through modifiers, order, etc.
func (_m *DiscountCondition) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDiscount queries the "discount" edge of the DiscountCondition entity.
func (_m *DiscountCondition) QueryDiscount() *DiscountQuery {
	return NewDiscountConditionClient(_m.config).QueryDiscount(_m)
}

// Update returns a builder for updating this DiscountCondition.
// Note that you need to call DiscountCondition.Unwrap() before calling this method if this DiscountCondition
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DiscountCondition) Update() *DiscountConditionUpdateOne {
	return NewDiscountConditionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DiscountCondition entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DiscountCondition) Unwrap() *DiscountCondition {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DiscountCondition is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DiscountCondition) String() string {
	var builder strings.Builder
	builder.WriteString("DiscountCondition(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedBy))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("discount_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DiscountID))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("values=")
	builder.WriteString(fmt.Sprintf("%v", _m.Values))
	builder.WriteByte(')')
	return builder.String()
}

// DiscountConditions is a parsable slice of DiscountCondition.
type DiscountConditions []*DiscountCondition
