// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/order"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/orderreturn"
)

// OrderReturn is the model entity for the OrderReturn schema.
type OrderReturn struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int64 `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy int64 `json:"updated_by,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID int64 `json:"tenant_id,omitempty"`
	// Version holds the value of the "version" field.
	Version int `json:"version,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID int `json:"order_id,omitempty"`
	// Status holds the value of the "status" field.
	Status orderreturn.Status `json:"status,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// RefundAmount holds the value of the "refund_amount" field.
	RefundAmount int64 `json:"refund_amount,omitempty"`
	// CurrencyCode holds the value of the "currency_code" field.
	CurrencyCode string `json:"currency_code,omitempty"`
	// Totals holds the value of the "totals" field.
	Totals map[string]interface{} `json:"totals,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OrderReturnQuery when eager-loading is set.
	Edges        OrderReturnEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OrderReturnEdges holds the relations/edges for other nodes in the graph.
type OrderReturnEdges struct {
	// Order holds the value of the order edge.
	Order *Order `json:"order,omitempty"`
	// Items holds the value of the items edge.
	Items []*ReturnItem `json:"items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OrderOrErr returns the Order value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrderReturnEdges) OrderOrErr() (*Order, error) {
	if e.Order != nil {
		return e.Order, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: order.Label}
	}
	return nil, &NotLoadedError{edge: "order"}
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e OrderReturnEdges) ItemsOrErr() ([]*ReturnItem, error) {
	if e.loadedTypes[1] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OrderReturn) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case orderreturn.FieldTotals:
			values[i] = new([]byte)
		case orderreturn.FieldID, orderreturn.FieldCreatedBy, orderreturn.FieldUpdatedBy, orderreturn.FieldTenantID, orderreturn.FieldVersion, orderreturn.FieldOrderID, orderreturn.FieldRefundAmount:
			values[i] = new(sql.NullInt64)
		case orderreturn.FieldStatus, orderreturn.FieldReason, orderreturn.FieldCurrencyCode:
			values[i] = new(sql.NullString)
		case orderreturn.FieldCreatedAt, orderreturn.FieldUpdatedAt, orderreturn.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OrderReturn fields.
func (_m *OrderReturn) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case orderreturn.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case orderreturn.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.Int64
			}
		case orderreturn.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.Int64
			}
		case orderreturn.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.Int64
			}
		case orderreturn.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		case orderreturn.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case orderreturn.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case orderreturn.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case orderreturn.FieldOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = int(value.Int64)
			}
		case orderreturn.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = orderreturn.Status(value.String)
			}
		case orderreturn.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case orderreturn.FieldRefundAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field refund_amount", values[i])
			} else if value.Valid {
				_m.RefundAmount = value.Int64
			}
		case orderreturn.FieldCurrencyCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency_code", values[i])
			} else if value.Valid {
				_m.CurrencyCode = value.String
			}
		case orderreturn.FieldTotals:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field totals", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Totals); err != nil {
					return fmt.Errorf("unmarshal field totals: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OrderReturn.
// This includes values selected through modifiers, order, etc.
func (_m *OrderReturn) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOrder queries the "order" edge of the OrderReturn entity.
func (_m *OrderReturn) QueryOrder() *OrderQuery {
	return NewOrderReturnClient(_m.config).QueryOrder(_m)
}

// QueryItems queries the "items" edge of the OrderReturn entity.
func (_m *OrderReturn) QueryItems() *ReturnItemQuery {
	return NewOrderReturnClient(_m.config).QueryItems(_m)
}

// Update returns a builder for updating this OrderReturn.
// Note that you need to call OrderReturn.Unwrap() before calling this method if this OrderReturn
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OrderReturn) Update() *OrderReturnUpdateOne {
	return NewOrderReturnClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OrderReturn entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OrderReturn) Unwrap() *OrderReturn {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OrderReturn is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OrderReturn) String() string {
	var builder strings.Builder
	builder.WriteString("OrderReturn(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedBy))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("refund_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefundAmount))
	builder.WriteString(", ")
	builder.WriteString("currency_code=")
	builder.WriteString(_m.CurrencyCode)
	builder.WriteString(", ")
	builder.WriteString("totals=")
	builder.WriteString(fmt.Sprintf("%v", _m.Totals))
	builder.WriteByte(')')
	return builder.String()
}

// OrderReturns is a parsable slice of OrderReturn.
type OrderReturns []*OrderReturn
