// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/paymentprovider"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/paymentsession"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/predicate"
)

// PaymentProviderQuery is the builder for querying PaymentProvider entities.
type PaymentProviderQuery struct {
	config
	ctx          *QueryContext
	order        []paymentprovider.OrderOption
	inters       []Interceptor
	predicates   []predicate.PaymentProvider
	withSessions *PaymentSessionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PaymentProviderQuery builder.
func (_q *PaymentProviderQuery) Where(ps ...predicate.PaymentProvider) *PaymentProviderQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PaymentProviderQuery) Limit(limit int) *PaymentProviderQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PaymentProviderQuery) Offset(offset int) *PaymentProviderQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PaymentProviderQuery) Unique(unique bool) *PaymentProviderQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PaymentProviderQuery) Order(o ...paymentprovider.OrderOption) *PaymentProviderQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySessions chains the current query on the "sessions" edge.
func (_q *PaymentProviderQuery) QuerySessions() *PaymentSessionQuery {
	query := (&PaymentSessionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(paymentprovider.Table, paymentprovider.FieldID, selector),
			sqlgraph.To(paymentsession.Table, paymentsession.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, paymentprovider.SessionsTable, paymentprovider.SessionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PaymentProvider entity from the query.
// Returns a *NotFoundError when no PaymentProvider was found.
func (_q *PaymentProviderQuery) First(ctx context.Context) (*PaymentProvider, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{paymentprovider.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PaymentProviderQuery) FirstX(ctx context.Context) *PaymentProvider {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PaymentProvider ID from the query.
// Returns a *NotFoundError when no PaymentProvider ID was found.
func (_q *PaymentProviderQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{paymentprovider.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PaymentProviderQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PaymentProvider entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PaymentProvider entity is found.
// Returns a *NotFoundError when no PaymentProvider entities are found.
func (_q *PaymentProviderQuery) Only(ctx context.Context) (*PaymentProvider, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{paymentprovider.Label}
	default:
		return nil, &NotSingularError{paymentprovider.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PaymentProviderQuery) OnlyX(ctx context.Context) *PaymentProvider {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PaymentProvider ID in the query.
// Returns a *NotSingularError when more than one PaymentProvider ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PaymentProviderQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{paymentprovider.Label}
	default:
		err = &NotSingularError{paymentprovider.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PaymentProviderQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PaymentProviders.
func (_q *PaymentProviderQuery) All(ctx context.Context) ([]*PaymentProvider, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PaymentProvider, *PaymentProviderQuery]()
	return withInterceptors[[]*PaymentProvider](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PaymentProviderQuery) AllX(ctx context.Context) []*PaymentProvider {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PaymentProvider IDs.
func (_q *PaymentProviderQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(paymentprovider.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PaymentProviderQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PaymentProviderQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PaymentProviderQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PaymentProviderQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PaymentProviderQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PaymentProviderQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PaymentProviderQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PaymentProviderQuery) Clone() *PaymentProviderQuery {
	if _q == nil {
		return nil
	}
	return &PaymentProviderQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]paymentprovider.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.PaymentProvider{}, _q.predicates...),
		withSessions: _q.withSessions.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSessions tells the query-builder to eager-load the nodes that are connected to
// the "sessions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PaymentProviderQuery) WithSessions(opts ...func(*PaymentSessionQuery)) *PaymentProviderQuery {
	query := (&PaymentSessionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSessions = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedBy int64 `json:"created_by,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PaymentProvider.Query().
//		GroupBy(paymentprovider.FieldCreatedBy).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PaymentProviderQuery) GroupBy(field string, fields ...string) *PaymentProviderGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PaymentProviderGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = paymentprovider.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedBy int64 `json:"created_by,omitempty"`
//	}
//
//	client.PaymentProvider.Query().
//		Select(paymentprovider.FieldCreatedBy).
//		Scan(ctx, &v)
func (_q *PaymentProviderQuery) Select(fields ...string) *PaymentProviderSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PaymentProviderSelect{PaymentProviderQuery: _q}
	sbuild.label = paymentprovider.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PaymentProviderSelect configured with the given aggregations.
func (_q *PaymentProviderQuery) Aggregate(fns ...AggregateFunc) *PaymentProviderSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PaymentProviderQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !paymentprovider.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PaymentProviderQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PaymentProvider, error) {
	var (
		nodes       = []*PaymentProvider{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withSessions != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PaymentProvider).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PaymentProvider{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSessions; query != nil {
		if err := _q.loadSessions(ctx, query, nodes,
			func(n *PaymentProvider) { n.Edges.Sessions = []*PaymentSession{} },
			func(n *PaymentProvider, e *PaymentSession) { n.Edges.Sessions = append(n.Edges.Sessions, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PaymentProviderQuery) loadSessions(ctx context.Context, query *PaymentSessionQuery, nodes []*PaymentProvider, init func(*PaymentProvider), assign func(*PaymentProvider, *PaymentSession)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*PaymentProvider)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.PaymentSession(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(paymentprovider.SessionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.payment_provider_sessions
		if fk == nil {
			return fmt.Errorf(`foreign-key "payment_provider_sessions" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "payment_provider_sessions" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *PaymentProviderQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PaymentProviderQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(paymentprovider.Table, paymentprovider.Columns, sqlgraph.NewFieldSpec(paymentprovider.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentprovider.FieldID)
		for i := range fields {
			if fields[i] != paymentprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PaymentProviderQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(paymentprovider.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = paymentprovider.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PaymentProviderGroupBy is the group-by builder for PaymentProvider entities.
type PaymentProviderGroupBy struct {
	selector
	build *PaymentProviderQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PaymentProviderGroupBy) Aggregate(fns ...AggregateFunc) *PaymentProviderGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PaymentProviderGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PaymentProviderQuery, *PaymentProviderGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PaymentProviderGroupBy) sqlScan(ctx context.Context, root *PaymentProviderQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PaymentProviderSelect is the builder for selecting fields of PaymentProvider entities.
type PaymentProviderSelect struct {
	*PaymentProviderQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PaymentProviderSelect) Aggregate(fns ...AggregateFunc) *PaymentProviderSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PaymentProviderSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PaymentProviderQuery, *PaymentProviderSelect](ctx, _s.PaymentProviderQuery, _s, _s.inters, v)
}

func (_s *PaymentProviderSelect) sqlScan(ctx context.Context, root *PaymentProviderQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
