// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/shippingoption"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/shippingprofile"
)

// ShippingProfileCreate is the builder for creating a ShippingProfile entity.
type ShippingProfileCreate struct {
	config
	mutation *ShippingProfileMutation
	hooks    []Hook
}

// SetCreatedBy sets the "created_by" field.
func (_c *ShippingProfileCreate) SetCreatedBy(v int64) *ShippingProfileCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *ShippingProfileCreate) SetNillableCreatedBy(v *int64) *ShippingProfileCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *ShippingProfileCreate) SetUpdatedBy(v int64) *ShippingProfileCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *ShippingProfileCreate) SetNillableUpdatedBy(v *int64) *ShippingProfileCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *ShippingProfileCreate) SetTenantID(v int64) *ShippingProfileCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *ShippingProfileCreate) SetNillableTenantID(v *int64) *ShippingProfileCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *ShippingProfileCreate) SetVersion(v int) *ShippingProfileCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *ShippingProfileCreate) SetNillableVersion(v *int) *ShippingProfileCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ShippingProfileCreate) SetCreatedAt(v time.Time) *ShippingProfileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ShippingProfileCreate) SetNillableCreatedAt(v *time.Time) *ShippingProfileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ShippingProfileCreate) SetUpdatedAt(v time.Time) *ShippingProfileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ShippingProfileCreate) SetNillableUpdatedAt(v *time.Time) *ShippingProfileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ShippingProfileCreate) SetDeletedAt(v time.Time) *ShippingProfileCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ShippingProfileCreate) SetNillableDeletedAt(v *time.Time) *ShippingProfileCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ShippingProfileCreate) SetName(v string) *ShippingProfileCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetProductType sets the "product_type" field.
func (_c *ShippingProfileCreate) SetProductType(v string) *ShippingProfileCreate {
	_c.mutation.SetProductType(v)
	return _c
}

// SetNillableProductType sets the "product_type" field if the given value is not nil.
func (_c *ShippingProfileCreate) SetNillableProductType(v *string) *ShippingProfileCreate {
	if v != nil {
		_c.SetProductType(*v)
	}
	return _c
}

// AddOptionIDs adds the "options" edge to the ShippingOption entity by IDs.
func (_c *ShippingProfileCreate) AddOptionIDs(ids ...int) *ShippingProfileCreate {
	_c.mutation.AddOptionIDs(ids...)
	return _c
}

// AddOptions adds the "options" edges to the ShippingOption entity.
func (_c *ShippingProfileCreate) AddOptions(v ...*ShippingOption) *ShippingProfileCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOptionIDs(ids...)
}

// Mutation returns the ShippingProfileMutation object of the builder.
func (_c *ShippingProfileCreate) Mutation() *ShippingProfileMutation {
	return _c.mutation
}

// Save creates the ShippingProfile in the database.
func (_c *ShippingProfileCreate) Save(ctx context.Context) (*ShippingProfile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ShippingProfileCreate) SaveX(ctx context.Context) *ShippingProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShippingProfileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShippingProfileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ShippingProfileCreate) defaults() {
	if _, ok := _c.mutation.Version(); !ok {
		v := shippingprofile.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := shippingprofile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := shippingprofile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ProductType(); !ok {
		v := shippingprofile.DefaultProductType
		_c.mutation.SetProductType(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ShippingProfileCreate) check() error {
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ShippingProfile.version"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ShippingProfile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ShippingProfile.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ShippingProfile.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := shippingprofile.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ShippingProfile.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProductType(); !ok {
		return &ValidationError{Name: "product_type", err: errors.New(`ent: missing required field "ShippingProfile.product_type"`)}
	}
	return nil
}

func (_c *ShippingProfileCreate) sqlSave(ctx context.Context) (*ShippingProfile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ShippingProfileCreate) createSpec() (*ShippingProfile, *sqlgraph.CreateSpec) {
	var (
		_node = &ShippingProfile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(shippingprofile.Table, sqlgraph.NewFieldSpec(shippingprofile.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(shippingprofile.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(shippingprofile.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(shippingprofile.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(shippingprofile.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(shippingprofile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(shippingprofile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(shippingprofile.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(shippingprofile.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ProductType(); ok {
		_spec.SetField(shippingprofile.FieldProductType, field.TypeString, value)
		_node.ProductType = value
	}
	if nodes := _c.mutation.OptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shippingprofile.OptionsTable,
			Columns: []string{shippingprofile.OptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shippingoption.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ShippingProfileCreateBulk is the builder for creating many ShippingProfile entities in bulk.
type ShippingProfileCreateBulk struct {
	config
	err      error
	builders []*ShippingProfileCreate
}

// Save creates the ShippingProfile entities in the database.
func (_c *ShippingProfileCreateBulk) Save(ctx context.Context) ([]*ShippingProfile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ShippingProfile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShippingProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ShippingProfileCreateBulk) SaveX(ctx context.Context) []*ShippingProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShippingProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShippingProfileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
