// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/predicate"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/product"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/variant"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/variantoptionvalue"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/variantprice"
)

// VariantUpdate is the builder for updating Variant entities.
type VariantUpdate struct {
	config
	hooks    []Hook
	mutation *VariantMutation
}

// Where appends a list predicates to the VariantUpdate builder.
func (_u *VariantUpdate) Where(ps ...predicate.Variant) *VariantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *VariantUpdate) SetCreatedBy(v int64) *VariantUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *VariantUpdate) SetNillableCreatedBy(v *int64) *VariantUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *VariantUpdate) AddCreatedBy(v int64) *VariantUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *VariantUpdate) ClearCreatedBy() *VariantUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *VariantUpdate) SetUpdatedBy(v int64) *VariantUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *VariantUpdate) SetNillableUpdatedBy(v *int64) *VariantUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *VariantUpdate) AddUpdatedBy(v int64) *VariantUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *VariantUpdate) ClearUpdatedBy() *VariantUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *VariantUpdate) SetTenantID(v int64) *VariantUpdate {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *VariantUpdate) SetNillableTenantID(v *int64) *VariantUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *VariantUpdate) AddTenantID(v int64) *VariantUpdate {
	_u.mutation.AddTenantID(v)
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *VariantUpdate) ClearTenantID() *VariantUpdate {
	_u.mutation.ClearTenantID()
	return _u
}

// SetVersion sets the "version" field.
func (_u *VariantUpdate) SetVersion(v int) *VariantUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *VariantUpdate) SetNillableVersion(v *int) *VariantUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *VariantUpdate) AddVersion(v int) *VariantUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VariantUpdate) SetUpdatedAt(v time.Time) *VariantUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *VariantUpdate) SetDeletedAt(v time.Time) *VariantUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *VariantUpdate) SetNillableDeletedAt(v *time.Time) *VariantUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *VariantUpdate) ClearDeletedAt() *VariantUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *VariantUpdate) SetProductID(v int) *VariantUpdate {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *VariantUpdate) SetNillableProductID(v *int) *VariantUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetSku sets the "sku" field.
func (_u *VariantUpdate) SetSku(v string) *VariantUpdate {
	_u.mutation.SetSku(v)
	return _u
}

// SetNillableSku sets the "sku" field if the given value is not nil.
func (_u *VariantUpdate) SetNillableSku(v *string) *VariantUpdate {
	if v != nil {
		_u.SetSku(*v)
	}
	return _u
}

// SetBarcode sets the "barcode" field.
func (_u *VariantUpdate) SetBarcode(v string) *VariantUpdate {
	_u.mutation.SetBarcode(v)
	return _u
}

// SetNillableBarcode sets the "barcode" field if the given value is not nil.
func (_u *VariantUpdate) SetNillableBarcode(v *string) *VariantUpdate {
	if v != nil {
		_u.SetBarcode(*v)
	}
	return _u
}

// ClearBarcode clears the value of the "barcode" field.
func (_u *VariantUpdate) ClearBarcode() *VariantUpdate {
	_u.mutation.ClearBarcode()
	return _u
}

// SetWeightG sets the "weight_g" field.
func (_u *VariantUpdate) SetWeightG(v int) *VariantUpdate {
	_u.mutation.ResetWeightG()
	_u.mutation.SetWeightG(v)
	return _u
}

// SetNillableWeightG sets the "weight_g" field if the given value is not nil.
func (_u *VariantUpdate) SetNillableWeightG(v *int) *VariantUpdate {
	if v != nil {
		_u.SetWeightG(*v)
	}
	return _u
}

// AddWeightG adds value to the "weight_g" field.
func (_u *VariantUpdate) AddWeightG(v int) *VariantUpdate {
	_u.mutation.AddWeightG(v)
	return _u
}

// ClearWeightG clears the value of the "weight_g" field.
func (_u *VariantUpdate) ClearWeightG() *VariantUpdate {
	_u.mutation.ClearWeightG()
	return _u
}

// SetAllowBackorder sets the "allow_backorder" field.
func (_u *VariantUpdate) SetAllowBackorder(v bool) *VariantUpdate {
	_u.mutation.SetAllowBackorder(v)
	return _u
}

// SetNillableAllowBackorder sets the "allow_backorder" field if the given value is not nil.
func (_u *VariantUpdate) SetNillableAllowBackorder(v *bool) *VariantUpdate {
	if v != nil {
		_u.SetAllowBackorder(*v)
	}
	return _u
}

// SetInventory sets the "inventory" field.
func (_u *VariantUpdate) SetInventory(v int) *VariantUpdate {
	_u.mutation.ResetInventory()
	_u.mutation.SetInventory(v)
	return _u
}

// SetNillableInventory sets the "inventory" field if the given value is not nil.
func (_u *VariantUpdate) SetNillableInventory(v *int) *VariantUpdate {
	if v != nil {
		_u.SetInventory(*v)
	}
	return _u
}

// AddInventory adds value to the "inventory" field.
func (_u *VariantUpdate) AddInventory(v int) *VariantUpdate {
	_u.mutation.AddInventory(v)
	return _u
}

// SetPosition sets the "position" field.
func (_u *VariantUpdate) SetPosition(v int) *VariantUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *VariantUpdate) SetNillablePosition(v *int) *VariantUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *VariantUpdate) AddPosition(v int) *VariantUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *VariantUpdate) SetProduct(v *Product) *VariantUpdate {
	return _u.SetProductID(v.ID)
}

// AddPriceIDs adds the "prices" edge to the VariantPrice entity by IDs.
func (_u *VariantUpdate) AddPriceIDs(ids ...int) *VariantUpdate {
	_u.mutation.AddPriceIDs(ids...)
	return _u
}

// AddPrices adds the "prices" edges to the VariantPrice entity.
func (_u *VariantUpdate) AddPrices(v ...*VariantPrice) *VariantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPriceIDs(ids...)
}

// AddOptionValueIDs adds the "option_values" edge to the VariantOptionValue entity by IDs.
func (_u *VariantUpdate) AddOptionValueIDs(ids ...int) *VariantUpdate {
	_u.mutation.AddOptionValueIDs(ids...)
	return _u
}

// AddOptionValues adds the "option_values" edges to the VariantOptionValue entity.
func (_u *VariantUpdate) AddOptionValues(v ...*VariantOptionValue) *VariantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOptionValueIDs(ids...)
}

// Mutation returns the VariantMutation object of the builder.
func (_u *VariantUpdate) Mutation() *VariantMutation {
	return _u.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *VariantUpdate) ClearProduct() *VariantUpdate {
	_u.mutation.ClearProduct()
	return _u
}

// ClearPrices clears all "prices" edges to the VariantPrice entity.
func (_u *VariantUpdate) ClearPrices() *VariantUpdate {
	_u.mutation.ClearPrices()
	return _u
}

// RemovePriceIDs removes the "prices" edge to VariantPrice entities by IDs.
func (_u *VariantUpdate) RemovePriceIDs(ids ...int) *VariantUpdate {
	_u.mutation.RemovePriceIDs(ids...)
	return _u
}

// RemovePrices removes "prices" edges to VariantPrice entities.
func (_u *VariantUpdate) RemovePrices(v ...*VariantPrice) *VariantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePriceIDs(ids...)
}

// ClearOptionValues clears all "option_values" edges to the VariantOptionValue entity.
func (_u *VariantUpdate) ClearOptionValues() *VariantUpdate {
	_u.mutation.ClearOptionValues()
	return _u
}

// RemoveOptionValueIDs removes the "option_values" edge to VariantOptionValue entities by IDs.
func (_u *VariantUpdate) RemoveOptionValueIDs(ids ...int) *VariantUpdate {
	_u.mutation.RemoveOptionValueIDs(ids...)
	return _u
}

// RemoveOptionValues removes "option_values" edges to VariantOptionValue entities.
func (_u *VariantUpdate) RemoveOptionValues(v ...*VariantOptionValue) *VariantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOptionValueIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VariantUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VariantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VariantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VariantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VariantUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := variant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VariantUpdate) check() error {
	if _u.mutation.ProductCleared() && len(_u.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Variant.product"`)
	}
	return nil
}

func (_u *VariantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(variant.Table, variant.Columns, sqlgraph.NewFieldSpec(variant.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(variant.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(variant.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(variant.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(variant.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(variant.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(variant.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(variant.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(variant.FieldTenantID, field.TypeInt64, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(variant.FieldTenantID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(variant.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(variant.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(variant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(variant.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(variant.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Sku(); ok {
		_spec.SetField(variant.FieldSku, field.TypeString, value)
	}
	if value, ok := _u.mutation.Barcode(); ok {
		_spec.SetField(variant.FieldBarcode, field.TypeString, value)
	}
	if _u.mutation.BarcodeCleared() {
		_spec.ClearField(variant.FieldBarcode, field.TypeString)
	}
	if value, ok := _u.mutation.WeightG(); ok {
		_spec.SetField(variant.FieldWeightG, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeightG(); ok {
		_spec.AddField(variant.FieldWeightG, field.TypeInt, value)
	}
	if _u.mutation.WeightGCleared() {
		_spec.ClearField(variant.FieldWeightG, field.TypeInt)
	}
	if value, ok := _u.mutation.AllowBackorder(); ok {
		_spec.SetField(variant.FieldAllowBackorder, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Inventory(); ok {
		_spec.SetField(variant.FieldInventory, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInventory(); ok {
		_spec.AddField(variant.FieldInventory, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(variant.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(variant.FieldPosition, field.TypeInt, value)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   variant.ProductTable,
			Columns: []string{variant.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   variant.ProductTable,
			Columns: []string{variant.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PricesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   variant.PricesTable,
			Columns: []string{variant.PricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(variantprice.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPricesIDs(); len(nodes) > 0 && !_u.mutation.PricesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   variant.PricesTable,
			Columns: []string{variant.PricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(variantprice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PricesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   variant.PricesTable,
			Columns: []string{variant.PricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(variantprice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OptionValuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   variant.OptionValuesTable,
			Columns: []string{variant.OptionValuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(variantoptionvalue.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOptionValuesIDs(); len(nodes) > 0 && !_u.mutation.OptionValuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   variant.OptionValuesTable,
			Columns: []string{variant.OptionValuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(variantoptionvalue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OptionValuesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   variant.OptionValuesTable,
			Columns: []string{variant.OptionValuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(variantoptionvalue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{variant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VariantUpdateOne is the builder for updating a single Variant entity.
type VariantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VariantMutation
}

// SetCreatedBy sets the "created_by" field.
func (_u *VariantUpdateOne) SetCreatedBy(v int64) *VariantUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *VariantUpdateOne) SetNillableCreatedBy(v *int64) *VariantUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *VariantUpdateOne) AddCreatedBy(v int64) *VariantUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *VariantUpdateOne) ClearCreatedBy() *VariantUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *VariantUpdateOne) SetUpdatedBy(v int64) *VariantUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *VariantUpdateOne) SetNillableUpdatedBy(v *int64) *VariantUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *VariantUpdateOne) AddUpdatedBy(v int64) *VariantUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *VariantUpdateOne) ClearUpdatedBy() *VariantUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *VariantUpdateOne) SetTenantID(v int64) *VariantUpdateOne {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *VariantUpdateOne) SetNillableTenantID(v *int64) *VariantUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *VariantUpdateOne) AddTenantID(v int64) *VariantUpdateOne {
	_u.mutation.AddTenantID(v)
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *VariantUpdateOne) ClearTenantID() *VariantUpdateOne {
	_u.mutation.ClearTenantID()
	return _u
}

// SetVersion sets the "version" field.
func (_u *VariantUpdateOne) SetVersion(v int) *VariantUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *VariantUpdateOne) SetNillableVersion(v *int) *VariantUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *VariantUpdateOne) AddVersion(v int) *VariantUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VariantUpdateOne) SetUpdatedAt(v time.Time) *VariantUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *VariantUpdateOne) SetDeletedAt(v time.Time) *VariantUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *VariantUpdateOne) SetNillableDeletedAt(v *time.Time) *VariantUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *VariantUpdateOne) ClearDeletedAt() *VariantUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *VariantUpdateOne) SetProductID(v int) *VariantUpdateOne {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *VariantUpdateOne) SetNillableProductID(v *int) *VariantUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetSku sets the "sku" field.
func (_u *VariantUpdateOne) SetSku(v string) *VariantUpdateOne {
	_u.mutation.SetSku(v)
	return _u
}

// SetNillableSku sets the "sku" field if the given value is not nil.
func (_u *VariantUpdateOne) SetNillableSku(v *string) *VariantUpdateOne {
	if v != nil {
		_u.SetSku(*v)
	}
	return _u
}

// SetBarcode sets the "barcode" field.
func (_u *VariantUpdateOne) SetBarcode(v string) *VariantUpdateOne {
	_u.mutation.SetBarcode(v)
	return _u
}

// SetNillableBarcode sets the "barcode" field if the given value is not nil.
func (_u *VariantUpdateOne) SetNillableBarcode(v *string) *VariantUpdateOne {
	if v != nil {
		_u.SetBarcode(*v)
	}
	return _u
}

// ClearBarcode clears the value of the "barcode" field.
func (_u *VariantUpdateOne) ClearBarcode() *VariantUpdateOne {
	_u.mutation.ClearBarcode()
	return _u
}

// SetWeightG sets the "weight_g" field.
func (_u *VariantUpdateOne) SetWeightG(v int) *VariantUpdateOne {
	_u.mutation.ResetWeightG()
	_u.mutation.SetWeightG(v)
	return _u
}

// SetNillableWeightG sets the "weight_g" field if the given value is not nil.
func (_u *VariantUpdateOne) SetNillableWeightG(v *int) *VariantUpdateOne {
	if v != nil {
		_u.SetWeightG(*v)
	}
	return _u
}

// AddWeightG adds value to the "weight_g" field.
func (_u *VariantUpdateOne) AddWeightG(v int) *VariantUpdateOne {
	_u.mutation.AddWeightG(v)
	return _u
}

// ClearWeightG clears the value of the "weight_g" field.
func (_u *VariantUpdateOne) ClearWeightG() *VariantUpdateOne {
	_u.mutation.ClearWeightG()
	return _u
}

// SetAllowBackorder sets the "allow_backorder" field.
func (_u *VariantUpdateOne) SetAllowBackorder(v bool) *VariantUpdateOne {
	_u.mutation.SetAllowBackorder(v)
	return _u
}

// SetNillableAllowBackorder sets the "allow_backorder" field if the given value is not nil.
func (_u *VariantUpdateOne) SetNillableAllowBackorder(v *bool) *VariantUpdateOne {
	if v != nil {
		_u.SetAllowBackorder(*v)
	}
	return _u
}

// SetInventory sets the "inventory" field.
func (_u *VariantUpdateOne) SetInventory(v int) *VariantUpdateOne {
	_u.mutation.ResetInventory()
	_u.mutation.SetInventory(v)
	return _u
}

// SetNillableInventory sets the "inventory" field if the given value is not nil.
func (_u *VariantUpdateOne) SetNillableInventory(v *int) *VariantUpdateOne {
	if v != nil {
		_u.SetInventory(*v)
	}
	return _u
}

// AddInventory adds value to the "inventory" field.
func (_u *VariantUpdateOne) AddInventory(v int) *VariantUpdateOne {
	_u.mutation.AddInventory(v)
	return _u
}

// SetPosition sets the "position" field.
func (_u *VariantUpdateOne) SetPosition(v int) *VariantUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *VariantUpdateOne) SetNillablePosition(v *int) *VariantUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *VariantUpdateOne) AddPosition(v int) *VariantUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *VariantUpdateOne) SetProduct(v *Product) *VariantUpdateOne {
	return _u.SetProductID(v.ID)
}

// AddPriceIDs adds the "prices" edge to the VariantPrice entity by IDs.
func (_u *VariantUpdateOne) AddPriceIDs(ids ...int) *VariantUpdateOne {
	_u.mutation.AddPriceIDs(ids...)
	return _u
}

// AddPrices adds the "prices" edges to the VariantPrice entity.
func (_u *VariantUpdateOne) AddPrices(v ...*VariantPrice) *VariantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPriceIDs(ids...)
}

// AddOptionValueIDs adds the "option_values" edge to the VariantOptionValue entity by IDs.
func (_u *VariantUpdateOne) AddOptionValueIDs(ids ...int) *VariantUpdateOne {
	_u.mutation.AddOptionValueIDs(ids...)
	return _u
}

// AddOptionValues adds the "option_values" edges to the VariantOptionValue entity.
func (_u *VariantUpdateOne) AddOptionValues(v ...*VariantOptionValue) *VariantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOptionValueIDs(ids...)
}

// Mutation returns the VariantMutation object of the builder.
func (_u *VariantUpdateOne) Mutation() *VariantMutation {
	return _u.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *VariantUpdateOne) ClearProduct() *VariantUpdateOne {
	_u.mutation.ClearProduct()
	return _u
}

// ClearPrices clears all "prices" edges to the VariantPrice entity.
func (_u *VariantUpdateOne) ClearPrices() *VariantUpdateOne {
	_u.mutation.ClearPrices()
	return _u
}

// RemovePriceIDs removes the "prices" edge to VariantPrice entities by IDs.
func (_u *VariantUpdateOne) RemovePriceIDs(ids ...int) *VariantUpdateOne {
	_u.mutation.RemovePriceIDs(ids...)
	return _u
}

// RemovePrices removes "prices" edges to VariantPrice entities.
func (_u *VariantUpdateOne) RemovePrices(v ...*VariantPrice) *VariantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePriceIDs(ids...)
}

// ClearOptionValues clears all "option_values" edges to the VariantOptionValue entity.
func (_u *VariantUpdateOne) ClearOptionValues() *VariantUpdateOne {
	_u.mutation.ClearOptionValues()
	return _u
}

// RemoveOptionValueIDs removes the "option_values" edge to VariantOptionValue entities by IDs.
func (_u *VariantUpdateOne) RemoveOptionValueIDs(ids ...int) *VariantUpdateOne {
	_u.mutation.RemoveOptionValueIDs(ids...)
	return _u
}

// RemoveOptionValues removes "option_values" edges to VariantOptionValue entities.
func (_u *VariantUpdateOne) RemoveOptionValues(v ...*VariantOptionValue) *VariantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOptionValueIDs(ids...)
}

// Where appends a list predicates to the VariantUpdate builder.
func (_u *VariantUpdateOne) Where(ps ...predicate.Variant) *VariantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VariantUpdateOne) Select(field string, fields ...string) *VariantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Variant entity.
func (_u *VariantUpdateOne) Save(ctx context.Context) (*Variant, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VariantUpdateOne) SaveX(ctx context.Context) *Variant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VariantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VariantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VariantUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := variant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VariantUpdateOne) check() error {
	if _u.mutation.ProductCleared() && len(_u.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Variant.product"`)
	}
	return nil
}

func (_u *VariantUpdateOne) sqlSave(ctx context.Context) (_node *Variant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(variant.Table, variant.Columns, sqlgraph.NewFieldSpec(variant.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Variant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, variant.FieldID)
		for _, f := range fields {
			if !variant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != variant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(variant.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(variant.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(variant.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(variant.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(variant.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(variant.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(variant.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(variant.FieldTenantID, field.TypeInt64, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(variant.FieldTenantID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(variant.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(variant.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(variant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(variant.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(variant.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Sku(); ok {
		_spec.SetField(variant.FieldSku, field.TypeString, value)
	}
	if value, ok := _u.mutation.Barcode(); ok {
		_spec.SetField(variant.FieldBarcode, field.TypeString, value)
	}
	if _u.mutation.BarcodeCleared() {
		_spec.ClearField(variant.FieldBarcode, field.TypeString)
	}
	if value, ok := _u.mutation.WeightG(); ok {
		_spec.SetField(variant.FieldWeightG, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeightG(); ok {
		_spec.AddField(variant.FieldWeightG, field.TypeInt, value)
	}
	if _u.mutation.WeightGCleared() {
		_spec.ClearField(variant.FieldWeightG, field.TypeInt)
	}
	if value, ok := _u.mutation.AllowBackorder(); ok {
		_spec.SetField(variant.FieldAllowBackorder, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Inventory(); ok {
		_spec.SetField(variant.FieldInventory, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInventory(); ok {
		_spec.AddField(variant.FieldInventory, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(variant.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(variant.FieldPosition, field.TypeInt, value)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   variant.ProductTable,
			Columns: []string{variant.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   variant.ProductTable,
			Columns: []string{variant.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PricesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   variant.PricesTable,
			Columns: []string{variant.PricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(variantprice.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPricesIDs(); len(nodes) > 0 && !_u.mutation.PricesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   variant.PricesTable,
			Columns: []string{variant.PricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(variantprice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PricesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   variant.PricesTable,
			Columns: []string{variant.PricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(variantprice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OptionValuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   variant.OptionValuesTable,
			Columns: []string{variant.OptionValuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(variantoptionvalue.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOptionValuesIDs(); len(nodes) > 0 && !_u.mutation.OptionValuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   variant.OptionValuesTable,
			Columns: []string{variant.OptionValuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(variantoptionvalue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OptionValuesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   variant.OptionValuesTable,
			Columns: []string{variant.OptionValuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(variantoptionvalue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Variant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{variant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
