// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/predicate"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/product"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/variant"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/variantoptionvalue"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/variantprice"
)

// VariantQuery is the builder for querying Variant entities.
type VariantQuery struct {
	config
	ctx              *QueryContext
	order            []variant.OrderOption
	inters           []Interceptor
	predicates       []predicate.Variant
	withProduct      *ProductQuery
	withPrices       *VariantPriceQuery
	withOptionValues *VariantOptionValueQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VariantQuery builder.
func (_q *VariantQuery) Where(ps ...predicate.Variant) *VariantQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *VariantQuery) Limit(limit int) *VariantQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *VariantQuery) Offset(offset int) *VariantQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *VariantQuery) Unique(unique bool) *VariantQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *VariantQuery) Order(o ...variant.OrderOption) *VariantQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProduct chains the current query on the "product" edge.
func (_q *VariantQuery) QueryProduct() *ProductQuery {
	query := (&ProductClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(variant.Table, variant.FieldID, selector),
			sqlgraph.To(product.Table, product.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, variant.ProductTable, variant.ProductColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPrices chains the current query on the "prices" edge.
func (_q *VariantQuery) QueryPrices() *VariantPriceQuery {
	query := (&VariantPriceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(variant.Table, variant.FieldID, selector),
			sqlgraph.To(variantprice.Table, variantprice.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, variant.PricesTable, variant.PricesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOptionValues chains the current query on the "option_values" edge.
func (_q *VariantQuery) QueryOptionValues() *VariantOptionValueQuery {
	query := (&VariantOptionValueClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(variant.Table, variant.FieldID, selector),
			sqlgraph.To(variantoptionvalue.Table, variantoptionvalue.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, variant.OptionValuesTable, variant.OptionValuesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Variant entity from the query.
// Returns a *NotFoundError when no Variant was found.
func (_q *VariantQuery) First(ctx context.Context) (*Variant, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{variant.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *VariantQuery) FirstX(ctx context.Context) *Variant {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Variant ID from the query.
// Returns a *NotFoundError when no Variant ID was found.
func (_q *VariantQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{variant.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *VariantQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Variant entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Variant entity is found.
// Returns a *NotFoundError when no Variant entities are found.
func (_q *VariantQuery) Only(ctx context.Context) (*Variant, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{variant.Label}
	default:
		return nil, &NotSingularError{variant.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *VariantQuery) OnlyX(ctx context.Context) *Variant {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Variant ID in the query.
// Returns a *NotSingularError when more than one Variant ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *VariantQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{variant.Label}
	default:
		err = &NotSingularError{variant.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *VariantQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Variants.
func (_q *VariantQuery) All(ctx context.Context) ([]*Variant, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Variant, *VariantQuery]()
	return withInterceptors[[]*Variant](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *VariantQuery) AllX(ctx context.Context) []*Variant {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Variant IDs.
func (_q *VariantQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(variant.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *VariantQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *VariantQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*VariantQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *VariantQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *VariantQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *VariantQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VariantQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *VariantQuery) Clone() *VariantQuery {
	if _q == nil {
		return nil
	}
	return &VariantQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]variant.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.Variant{}, _q.predicates...),
		withProduct:      _q.withProduct.Clone(),
		withPrices:       _q.withPrices.Clone(),
		withOptionValues: _q.withOptionValues.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithProduct tells the query-builder to eager-load the nodes that are connected to
// the "product" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VariantQuery) WithProduct(opts ...func(*ProductQuery)) *VariantQuery {
	query := (&ProductClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProduct = query
	return _q
}

// WithPrices tells the query-builder to eager-load the nodes that are connected to
// the "prices" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VariantQuery) WithPrices(opts ...func(*VariantPriceQuery)) *VariantQuery {
	query := (&VariantPriceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPrices = query
	return _q
}

// WithOptionValues tells the query-builder to eager-load the nodes that are connected to
// the "option_values" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VariantQuery) WithOptionValues(opts ...func(*VariantOptionValueQuery)) *VariantQuery {
	query := (&VariantOptionValueClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOptionValues = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedBy int64 `json:"created_by,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Variant.Query().
//		GroupBy(variant.FieldCreatedBy).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *VariantQuery) GroupBy(field string, fields ...string) *VariantGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VariantGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = variant.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedBy int64 `json:"created_by,omitempty"`
//	}
//
//	client.Variant.Query().
//		Select(variant.FieldCreatedBy).
//		Scan(ctx, &v)
func (_q *VariantQuery) Select(fields ...string) *VariantSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &VariantSelect{VariantQuery: _q}
	sbuild.label = variant.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VariantSelect configured with the given aggregations.
func (_q *VariantQuery) Aggregate(fns ...AggregateFunc) *VariantSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *VariantQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !variant.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *VariantQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Variant, error) {
	var (
		nodes       = []*Variant{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withProduct != nil,
			_q.withPrices != nil,
			_q.withOptionValues != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Variant).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Variant{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProduct; query != nil {
		if err := _q.loadProduct(ctx, query, nodes, nil,
			func(n *Variant, e *Product) { n.Edges.Product = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPrices; query != nil {
		if err := _q.loadPrices(ctx, query, nodes,
			func(n *Variant) { n.Edges.Prices = []*VariantPrice{} },
			func(n *Variant, e *VariantPrice) { n.Edges.Prices = append(n.Edges.Prices, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withOptionValues; query != nil {
		if err := _q.loadOptionValues(ctx, query, nodes,
			func(n *Variant) { n.Edges.OptionValues = []*VariantOptionValue{} },
			func(n *Variant, e *VariantOptionValue) { n.Edges.OptionValues = append(n.Edges.OptionValues, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *VariantQuery) loadProduct(ctx context.Context, query *ProductQuery, nodes []*Variant, init func(*Variant), assign func(*Variant, *Product)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Variant)
	for i := range nodes {
		fk := nodes[i].ProductID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(product.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "product_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *VariantQuery) loadPrices(ctx context.Context, query *VariantPriceQuery, nodes []*Variant, init func(*Variant), assign func(*Variant, *VariantPrice)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Variant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(variantprice.FieldVariantID)
	}
	query.Where(predicate.VariantPrice(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(variant.PricesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.VariantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "variant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *VariantQuery) loadOptionValues(ctx context.Context, query *VariantOptionValueQuery, nodes []*Variant, init func(*Variant), assign func(*Variant, *VariantOptionValue)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Variant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(variantoptionvalue.FieldVariantID)
	}
	query.Where(predicate.VariantOptionValue(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(variant.OptionValuesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.VariantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "variant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *VariantQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *VariantQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(variant.Table, variant.Columns, sqlgraph.NewFieldSpec(variant.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, variant.FieldID)
		for i := range fields {
			if fields[i] != variant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withProduct != nil {
			_spec.Node.AddColumnOnce(variant.FieldProductID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *VariantQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(variant.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = variant.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VariantGroupBy is the group-by builder for Variant entities.
type VariantGroupBy struct {
	selector
	build *VariantQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *VariantGroupBy) Aggregate(fns ...AggregateFunc) *VariantGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *VariantGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VariantQuery, *VariantGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *VariantGroupBy) sqlScan(ctx context.Context, root *VariantQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VariantSelect is the builder for selecting fields of Variant entities.
type VariantSelect struct {
	*VariantQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *VariantSelect) Aggregate(fns ...AggregateFunc) *VariantSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *VariantSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VariantQuery, *VariantSelect](ctx, _s.VariantQuery, _s, _s.inters, v)
}

func (_s *VariantSelect) sqlScan(ctx context.Context, root *VariantQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
