// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/product"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/variant"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/variantoptionvalue"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/variantprice"
)

// VariantCreate is the builder for creating a Variant entity.
type VariantCreate struct {
	config
	mutation *VariantMutation
	hooks    []Hook
}

// SetCreatedBy sets the "created_by" field.
func (_c *VariantCreate) SetCreatedBy(v int64) *VariantCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *VariantCreate) SetNillableCreatedBy(v *int64) *VariantCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *VariantCreate) SetUpdatedBy(v int64) *VariantCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *VariantCreate) SetNillableUpdatedBy(v *int64) *VariantCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *VariantCreate) SetTenantID(v int64) *VariantCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *VariantCreate) SetNillableTenantID(v *int64) *VariantCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *VariantCreate) SetVersion(v int) *VariantCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *VariantCreate) SetNillableVersion(v *int) *VariantCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VariantCreate) SetCreatedAt(v time.Time) *VariantCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VariantCreate) SetNillableCreatedAt(v *time.Time) *VariantCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VariantCreate) SetUpdatedAt(v time.Time) *VariantCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VariantCreate) SetNillableUpdatedAt(v *time.Time) *VariantCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *VariantCreate) SetDeletedAt(v time.Time) *VariantCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *VariantCreate) SetNillableDeletedAt(v *time.Time) *VariantCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetProductID sets the "product_id" field.
func (_c *VariantCreate) SetProductID(v int) *VariantCreate {
	_c.mutation.SetProductID(v)
	return _c
}

// SetSku sets the "sku" field.
func (_c *VariantCreate) SetSku(v string) *VariantCreate {
	_c.mutation.SetSku(v)
	return _c
}

// SetBarcode sets the "barcode" field.
func (_c *VariantCreate) SetBarcode(v string) *VariantCreate {
	_c.mutation.SetBarcode(v)
	return _c
}

// SetNillableBarcode sets the "barcode" field if the given value is not nil.
func (_c *VariantCreate) SetNillableBarcode(v *string) *VariantCreate {
	if v != nil {
		_c.SetBarcode(*v)
	}
	return _c
}

// SetWeightG sets the "weight_g" field.
func (_c *VariantCreate) SetWeightG(v int) *VariantCreate {
	_c.mutation.SetWeightG(v)
	return _c
}

// SetNillableWeightG sets the "weight_g" field if the given value is not nil.
func (_c *VariantCreate) SetNillableWeightG(v *int) *VariantCreate {
	if v != nil {
		_c.SetWeightG(*v)
	}
	return _c
}

// SetAllowBackorder sets the "allow_backorder" field.
func (_c *VariantCreate) SetAllowBackorder(v bool) *VariantCreate {
	_c.mutation.SetAllowBackorder(v)
	return _c
}

// SetNillableAllowBackorder sets the "allow_backorder" field if the given value is not nil.
func (_c *VariantCreate) SetNillableAllowBackorder(v *bool) *VariantCreate {
	if v != nil {
		_c.SetAllowBackorder(*v)
	}
	return _c
}

// SetInventory sets the "inventory" field.
func (_c *VariantCreate) SetInventory(v int) *VariantCreate {
	_c.mutation.SetInventory(v)
	return _c
}

// SetNillableInventory sets the "inventory" field if the given value is not nil.
func (_c *VariantCreate) SetNillableInventory(v *int) *VariantCreate {
	if v != nil {
		_c.SetInventory(*v)
	}
	return _c
}

// SetPosition sets the "position" field.
func (_c *VariantCreate) SetPosition(v int) *VariantCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_c *VariantCreate) SetNillablePosition(v *int) *VariantCreate {
	if v != nil {
		_c.SetPosition(*v)
	}
	return _c
}

// SetProduct sets the "product" edge to the Product entity.
func (_c *VariantCreate) SetProduct(v *Product) *VariantCreate {
	return _c.SetProductID(v.ID)
}

// AddPriceIDs adds the "prices" edge to the VariantPrice entity by IDs.
func (_c *VariantCreate) AddPriceIDs(ids ...int) *VariantCreate {
	_c.mutation.AddPriceIDs(ids...)
	return _c
}

// AddPrices adds the "prices" edges to the VariantPrice entity.
func (_c *VariantCreate) AddPrices(v ...*VariantPrice) *VariantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPriceIDs(ids...)
}

// AddOptionValueIDs adds the "option_values" edge to the VariantOptionValue entity by IDs.
func (_c *VariantCreate) AddOptionValueIDs(ids ...int) *VariantCreate {
	_c.mutation.AddOptionValueIDs(ids...)
	return _c
}

// AddOptionValues adds the "option_values" edges to the VariantOptionValue entity.
func (_c *VariantCreate) AddOptionValues(v ...*VariantOptionValue) *VariantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOptionValueIDs(ids...)
}

// Mutation returns the VariantMutation object of the builder.
func (_c *VariantCreate) Mutation() *VariantMutation {
	return _c.mutation
}

// Save creates the Variant in the database.
func (_c *VariantCreate) Save(ctx context.Context) (*Variant, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VariantCreate) SaveX(ctx context.Context) *Variant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VariantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VariantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VariantCreate) defaults() {
	if _, ok := _c.mutation.Version(); !ok {
		v := variant.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := variant.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := variant.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Barcode(); !ok {
		v := variant.DefaultBarcode
		_c.mutation.SetBarcode(v)
	}
	if _, ok := _c.mutation.AllowBackorder(); !ok {
		v := variant.DefaultAllowBackorder
		_c.mutation.SetAllowBackorder(v)
	}
	if _, ok := _c.mutation.Inventory(); !ok {
		v := variant.DefaultInventory
		_c.mutation.SetInventory(v)
	}
	if _, ok := _c.mutation.Position(); !ok {
		v := variant.DefaultPosition
		_c.mutation.SetPosition(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VariantCreate) check() error {
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Variant.version"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Variant.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Variant.updated_at"`)}
	}
	if _, ok := _c.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "Variant.product_id"`)}
	}
	if _, ok := _c.mutation.Sku(); !ok {
		return &ValidationError{Name: "sku", err: errors.New(`ent: missing required field "Variant.sku"`)}
	}
	if _, ok := _c.mutation.AllowBackorder(); !ok {
		return &ValidationError{Name: "allow_backorder", err: errors.New(`ent: missing required field "Variant.allow_backorder"`)}
	}
	if _, ok := _c.mutation.Inventory(); !ok {
		return &ValidationError{Name: "inventory", err: errors.New(`ent: missing required field "Variant.inventory"`)}
	}
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "Variant.position"`)}
	}
	if len(_c.mutation.ProductIDs()) == 0 {
		return &ValidationError{Name: "product", err: errors.New(`ent: missing required edge "Variant.product"`)}
	}
	return nil
}

func (_c *VariantCreate) sqlSave(ctx context.Context) (*Variant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VariantCreate) createSpec() (*Variant, *sqlgraph.CreateSpec) {
	var (
		_node = &Variant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(variant.Table, sqlgraph.NewFieldSpec(variant.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(variant.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(variant.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(variant.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(variant.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(variant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(variant.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(variant.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Sku(); ok {
		_spec.SetField(variant.FieldSku, field.TypeString, value)
		_node.Sku = value
	}
	if value, ok := _c.mutation.Barcode(); ok {
		_spec.SetField(variant.FieldBarcode, field.TypeString, value)
		_node.Barcode = value
	}
	if value, ok := _c.mutation.WeightG(); ok {
		_spec.SetField(variant.FieldWeightG, field.TypeInt, value)
		_node.WeightG = value
	}
	if value, ok := _c.mutation.AllowBackorder(); ok {
		_spec.SetField(variant.FieldAllowBackorder, field.TypeBool, value)
		_node.AllowBackorder = value
	}
	if value, ok := _c.mutation.Inventory(); ok {
		_spec.SetField(variant.FieldInventory, field.TypeInt, value)
		_node.Inventory = value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(variant.FieldPosition, field.TypeInt, value)
		_node.Position = value
	}
	if nodes := _c.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   variant.ProductTable,
			Columns: []string{variant.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProductID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PricesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   variant.PricesTable,
			Columns: []string{variant.PricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(variantprice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OptionValuesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   variant.OptionValuesTable,
			Columns: []string{variant.OptionValuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(variantoptionvalue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// VariantCreateBulk is the builder for creating many Variant entities in bulk.
type VariantCreateBulk struct {
	config
	err      error
	builders []*VariantCreate
}

// Save creates the Variant entities in the database.
func (_c *VariantCreateBulk) Save(ctx context.Context) ([]*Variant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Variant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VariantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VariantCreateBulk) SaveX(ctx context.Context) []*Variant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VariantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VariantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
