// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/predicate"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/variantoptionvalue"
)

// VariantOptionValueDelete is the builder for deleting a VariantOptionValue entity.
type VariantOptionValueDelete struct {
	config
	hooks    []Hook
	mutation *VariantOptionValueMutation
}

// Where appends a list predicates to the VariantOptionValueDelete builder.
func (_d *VariantOptionValueDelete) Where(ps ...predicate.VariantOptionValue) *VariantOptionValueDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *VariantOptionValueDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *VariantOptionValueDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *VariantOptionValueDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(variantoptionvalue.Table, sqlgraph.NewFieldSpec(variantoptionvalue.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// VariantOptionValueDeleteOne is the builder for deleting a single VariantOptionValue entity.
type VariantOptionValueDeleteOne struct {
	_d *VariantOptionValueDelete
}

// Where appends a list predicates to the VariantOptionValueDelete builder.
func (_d *VariantOptionValueDeleteOne) Where(ps ...predicate.VariantOptionValue) *VariantOptionValueDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *VariantOptionValueDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{variantoptionvalue.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *VariantOptionValueDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
