// Code generated by ent, DO NOT EDIT.

package formdefinitiontranslation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldLTE(FieldID, id))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEQ(FieldUpdatedBy, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEQ(FieldTenantID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEQ(FieldVersion, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEQ(FieldDeletedAt, v))
}

// FormDefinitionID applies equality check predicate on the "form_definition_id" field. It's identical to FormDefinitionIDEQ.
func FormDefinitionID(v int) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEQ(FieldFormDefinitionID, v))
}

// Locale applies equality check predicate on the "locale" field. It's identical to LocaleEQ.
func Locale(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEQ(FieldLocale, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEQ(FieldTitle, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNotNull(FieldUpdatedBy))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int64) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNotNull(FieldTenantID))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldLTE(FieldVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNotNull(FieldDeletedAt))
}

// FormDefinitionIDEQ applies the EQ predicate on the "form_definition_id" field.
func FormDefinitionIDEQ(v int) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEQ(FieldFormDefinitionID, v))
}

// FormDefinitionIDNEQ applies the NEQ predicate on the "form_definition_id" field.
func FormDefinitionIDNEQ(v int) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNEQ(FieldFormDefinitionID, v))
}

// FormDefinitionIDIn applies the In predicate on the "form_definition_id" field.
func FormDefinitionIDIn(vs ...int) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldIn(FieldFormDefinitionID, vs...))
}

// FormDefinitionIDNotIn applies the NotIn predicate on the "form_definition_id" field.
func FormDefinitionIDNotIn(vs ...int) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNotIn(FieldFormDefinitionID, vs...))
}

// LocaleEQ applies the EQ predicate on the "locale" field.
func LocaleEQ(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEQ(FieldLocale, v))
}

// LocaleNEQ applies the NEQ predicate on the "locale" field.
func LocaleNEQ(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNEQ(FieldLocale, v))
}

// LocaleIn applies the In predicate on the "locale" field.
func LocaleIn(vs ...string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldIn(FieldLocale, vs...))
}

// LocaleNotIn applies the NotIn predicate on the "locale" field.
func LocaleNotIn(vs ...string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNotIn(FieldLocale, vs...))
}

// LocaleGT applies the GT predicate on the "locale" field.
func LocaleGT(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldGT(FieldLocale, v))
}

// LocaleGTE applies the GTE predicate on the "locale" field.
func LocaleGTE(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldGTE(FieldLocale, v))
}

// LocaleLT applies the LT predicate on the "locale" field.
func LocaleLT(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldLT(FieldLocale, v))
}

// LocaleLTE applies the LTE predicate on the "locale" field.
func LocaleLTE(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldLTE(FieldLocale, v))
}

// LocaleContains applies the Contains predicate on the "locale" field.
func LocaleContains(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldContains(FieldLocale, v))
}

// LocaleHasPrefix applies the HasPrefix predicate on the "locale" field.
func LocaleHasPrefix(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldHasPrefix(FieldLocale, v))
}

// LocaleHasSuffix applies the HasSuffix predicate on the "locale" field.
func LocaleHasSuffix(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldHasSuffix(FieldLocale, v))
}

// LocaleEqualFold applies the EqualFold predicate on the "locale" field.
func LocaleEqualFold(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEqualFold(FieldLocale, v))
}

// LocaleContainsFold applies the ContainsFold predicate on the "locale" field.
func LocaleContainsFold(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldContainsFold(FieldLocale, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldContainsFold(FieldTitle, v))
}

// FieldLabelsIsNil applies the IsNil predicate on the "field_labels" field.
func FieldLabelsIsNil() predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldIsNull(FieldFieldLabels))
}

// FieldLabelsNotNil applies the NotNil predicate on the "field_labels" field.
func FieldLabelsNotNil() predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.FieldNotNull(FieldFieldLabels))
}

// HasFormDefinition applies the HasEdge predicate on the "form_definition" edge.
func HasFormDefinition() predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FormDefinitionTable, FormDefinitionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFormDefinitionWith applies the HasEdge predicate on the "form_definition" edge with a given conditions (other predicates).
func HasFormDefinitionWith(preds ...predicate.FormDefinition) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(func(s *sql.Selector) {
		step := newFormDefinitionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FormDefinitionTranslation) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FormDefinitionTranslation) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FormDefinitionTranslation) predicate.FormDefinitionTranslation {
	return predicate.FormDefinitionTranslation(sql.NotPredicates(p))
}
