// Code generated by ent, DO NOT EDIT.

package blogposttranslation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLTE(FieldID, id))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldUpdatedBy, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldTenantID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldVersion, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldDeletedAt, v))
}

// BlogPostID applies equality check predicate on the "blog_post_id" field. It's identical to BlogPostIDEQ.
func BlogPostID(v int) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldBlogPostID, v))
}

// Locale applies equality check predicate on the "locale" field. It's identical to LocaleEQ.
func Locale(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldLocale, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldTitle, v))
}

// Excerpt applies equality check predicate on the "excerpt" field. It's identical to ExcerptEQ.
func Excerpt(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldExcerpt, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldContent, v))
}

// SeoTitle applies equality check predicate on the "seo_title" field. It's identical to SeoTitleEQ.
func SeoTitle(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldSeoTitle, v))
}

// SeoDesc applies equality check predicate on the "seo_desc" field. It's identical to SeoDescEQ.
func SeoDesc(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldSeoDesc, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNotNull(FieldUpdatedBy))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int64) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNotNull(FieldTenantID))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLTE(FieldVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNotNull(FieldDeletedAt))
}

// BlogPostIDEQ applies the EQ predicate on the "blog_post_id" field.
func BlogPostIDEQ(v int) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldBlogPostID, v))
}

// BlogPostIDNEQ applies the NEQ predicate on the "blog_post_id" field.
func BlogPostIDNEQ(v int) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNEQ(FieldBlogPostID, v))
}

// BlogPostIDIn applies the In predicate on the "blog_post_id" field.
func BlogPostIDIn(vs ...int) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldIn(FieldBlogPostID, vs...))
}

// BlogPostIDNotIn applies the NotIn predicate on the "blog_post_id" field.
func BlogPostIDNotIn(vs ...int) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNotIn(FieldBlogPostID, vs...))
}

// LocaleEQ applies the EQ predicate on the "locale" field.
func LocaleEQ(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldLocale, v))
}

// LocaleNEQ applies the NEQ predicate on the "locale" field.
func LocaleNEQ(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNEQ(FieldLocale, v))
}

// LocaleIn applies the In predicate on the "locale" field.
func LocaleIn(vs ...string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldIn(FieldLocale, vs...))
}

// LocaleNotIn applies the NotIn predicate on the "locale" field.
func LocaleNotIn(vs ...string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNotIn(FieldLocale, vs...))
}

// LocaleGT applies the GT predicate on the "locale" field.
func LocaleGT(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGT(FieldLocale, v))
}

// LocaleGTE applies the GTE predicate on the "locale" field.
func LocaleGTE(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGTE(FieldLocale, v))
}

// LocaleLT applies the LT predicate on the "locale" field.
func LocaleLT(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLT(FieldLocale, v))
}

// LocaleLTE applies the LTE predicate on the "locale" field.
func LocaleLTE(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLTE(FieldLocale, v))
}

// LocaleContains applies the Contains predicate on the "locale" field.
func LocaleContains(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldContains(FieldLocale, v))
}

// LocaleHasPrefix applies the HasPrefix predicate on the "locale" field.
func LocaleHasPrefix(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldHasPrefix(FieldLocale, v))
}

// LocaleHasSuffix applies the HasSuffix predicate on the "locale" field.
func LocaleHasSuffix(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldHasSuffix(FieldLocale, v))
}

// LocaleEqualFold applies the EqualFold predicate on the "locale" field.
func LocaleEqualFold(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEqualFold(FieldLocale, v))
}

// LocaleContainsFold applies the ContainsFold predicate on the "locale" field.
func LocaleContainsFold(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldContainsFold(FieldLocale, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldContainsFold(FieldTitle, v))
}

// ExcerptEQ applies the EQ predicate on the "excerpt" field.
func ExcerptEQ(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldExcerpt, v))
}

// ExcerptNEQ applies the NEQ predicate on the "excerpt" field.
func ExcerptNEQ(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNEQ(FieldExcerpt, v))
}

// ExcerptIn applies the In predicate on the "excerpt" field.
func ExcerptIn(vs ...string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldIn(FieldExcerpt, vs...))
}

// ExcerptNotIn applies the NotIn predicate on the "excerpt" field.
func ExcerptNotIn(vs ...string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNotIn(FieldExcerpt, vs...))
}

// ExcerptGT applies the GT predicate on the "excerpt" field.
func ExcerptGT(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGT(FieldExcerpt, v))
}

// ExcerptGTE applies the GTE predicate on the "excerpt" field.
func ExcerptGTE(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGTE(FieldExcerpt, v))
}

// ExcerptLT applies the LT predicate on the "excerpt" field.
func ExcerptLT(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLT(FieldExcerpt, v))
}

// ExcerptLTE applies the LTE predicate on the "excerpt" field.
func ExcerptLTE(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLTE(FieldExcerpt, v))
}

// ExcerptContains applies the Contains predicate on the "excerpt" field.
func ExcerptContains(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldContains(FieldExcerpt, v))
}

// ExcerptHasPrefix applies the HasPrefix predicate on the "excerpt" field.
func ExcerptHasPrefix(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldHasPrefix(FieldExcerpt, v))
}

// ExcerptHasSuffix applies the HasSuffix predicate on the "excerpt" field.
func ExcerptHasSuffix(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldHasSuffix(FieldExcerpt, v))
}

// ExcerptIsNil applies the IsNil predicate on the "excerpt" field.
func ExcerptIsNil() predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldIsNull(FieldExcerpt))
}

// ExcerptNotNil applies the NotNil predicate on the "excerpt" field.
func ExcerptNotNil() predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNotNull(FieldExcerpt))
}

// ExcerptEqualFold applies the EqualFold predicate on the "excerpt" field.
func ExcerptEqualFold(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEqualFold(FieldExcerpt, v))
}

// ExcerptContainsFold applies the ContainsFold predicate on the "excerpt" field.
func ExcerptContainsFold(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldContainsFold(FieldExcerpt, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldHasSuffix(FieldContent, v))
}

// ContentIsNil applies the IsNil predicate on the "content" field.
func ContentIsNil() predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldIsNull(FieldContent))
}

// ContentNotNil applies the NotNil predicate on the "content" field.
func ContentNotNil() predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNotNull(FieldContent))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldContainsFold(FieldContent, v))
}

// SeoTitleEQ applies the EQ predicate on the "seo_title" field.
func SeoTitleEQ(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldSeoTitle, v))
}

// SeoTitleNEQ applies the NEQ predicate on the "seo_title" field.
func SeoTitleNEQ(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNEQ(FieldSeoTitle, v))
}

// SeoTitleIn applies the In predicate on the "seo_title" field.
func SeoTitleIn(vs ...string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldIn(FieldSeoTitle, vs...))
}

// SeoTitleNotIn applies the NotIn predicate on the "seo_title" field.
func SeoTitleNotIn(vs ...string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNotIn(FieldSeoTitle, vs...))
}

// SeoTitleGT applies the GT predicate on the "seo_title" field.
func SeoTitleGT(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGT(FieldSeoTitle, v))
}

// SeoTitleGTE applies the GTE predicate on the "seo_title" field.
func SeoTitleGTE(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGTE(FieldSeoTitle, v))
}

// SeoTitleLT applies the LT predicate on the "seo_title" field.
func SeoTitleLT(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLT(FieldSeoTitle, v))
}

// SeoTitleLTE applies the LTE predicate on the "seo_title" field.
func SeoTitleLTE(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLTE(FieldSeoTitle, v))
}

// SeoTitleContains applies the Contains predicate on the "seo_title" field.
func SeoTitleContains(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldContains(FieldSeoTitle, v))
}

// SeoTitleHasPrefix applies the HasPrefix predicate on the "seo_title" field.
func SeoTitleHasPrefix(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldHasPrefix(FieldSeoTitle, v))
}

// SeoTitleHasSuffix applies the HasSuffix predicate on the "seo_title" field.
func SeoTitleHasSuffix(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldHasSuffix(FieldSeoTitle, v))
}

// SeoTitleIsNil applies the IsNil predicate on the "seo_title" field.
func SeoTitleIsNil() predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldIsNull(FieldSeoTitle))
}

// SeoTitleNotNil applies the NotNil predicate on the "seo_title" field.
func SeoTitleNotNil() predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNotNull(FieldSeoTitle))
}

// SeoTitleEqualFold applies the EqualFold predicate on the "seo_title" field.
func SeoTitleEqualFold(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEqualFold(FieldSeoTitle, v))
}

// SeoTitleContainsFold applies the ContainsFold predicate on the "seo_title" field.
func SeoTitleContainsFold(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldContainsFold(FieldSeoTitle, v))
}

// SeoDescEQ applies the EQ predicate on the "seo_desc" field.
func SeoDescEQ(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEQ(FieldSeoDesc, v))
}

// SeoDescNEQ applies the NEQ predicate on the "seo_desc" field.
func SeoDescNEQ(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNEQ(FieldSeoDesc, v))
}

// SeoDescIn applies the In predicate on the "seo_desc" field.
func SeoDescIn(vs ...string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldIn(FieldSeoDesc, vs...))
}

// SeoDescNotIn applies the NotIn predicate on the "seo_desc" field.
func SeoDescNotIn(vs ...string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNotIn(FieldSeoDesc, vs...))
}

// SeoDescGT applies the GT predicate on the "seo_desc" field.
func SeoDescGT(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGT(FieldSeoDesc, v))
}

// SeoDescGTE applies the GTE predicate on the "seo_desc" field.
func SeoDescGTE(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldGTE(FieldSeoDesc, v))
}

// SeoDescLT applies the LT predicate on the "seo_desc" field.
func SeoDescLT(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLT(FieldSeoDesc, v))
}

// SeoDescLTE applies the LTE predicate on the "seo_desc" field.
func SeoDescLTE(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldLTE(FieldSeoDesc, v))
}

// SeoDescContains applies the Contains predicate on the "seo_desc" field.
func SeoDescContains(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldContains(FieldSeoDesc, v))
}

// SeoDescHasPrefix applies the HasPrefix predicate on the "seo_desc" field.
func SeoDescHasPrefix(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldHasPrefix(FieldSeoDesc, v))
}

// SeoDescHasSuffix applies the HasSuffix predicate on the "seo_desc" field.
func SeoDescHasSuffix(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldHasSuffix(FieldSeoDesc, v))
}

// SeoDescIsNil applies the IsNil predicate on the "seo_desc" field.
func SeoDescIsNil() predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldIsNull(FieldSeoDesc))
}

// SeoDescNotNil applies the NotNil predicate on the "seo_desc" field.
func SeoDescNotNil() predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldNotNull(FieldSeoDesc))
}

// SeoDescEqualFold applies the EqualFold predicate on the "seo_desc" field.
func SeoDescEqualFold(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldEqualFold(FieldSeoDesc, v))
}

// SeoDescContainsFold applies the ContainsFold predicate on the "seo_desc" field.
func SeoDescContainsFold(v string) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.FieldContainsFold(FieldSeoDesc, v))
}

// HasBlogPost applies the HasEdge predicate on the "blog_post" edge.
func HasBlogPost() predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BlogPostTable, BlogPostColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBlogPostWith applies the HasEdge predicate on the "blog_post" edge with a given conditions (other predicates).
func HasBlogPostWith(preds ...predicate.BlogPost) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(func(s *sql.Selector) {
		step := newBlogPostStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BlogPostTranslation) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BlogPostTranslation) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BlogPostTranslation) predicate.BlogPostTranslation {
	return predicate.BlogPostTranslation(sql.NotPredicates(p))
}
