// Code generated by ent, DO NOT EDIT.

package fulfillment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Snowitty-Re/e-fiber-admin/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLTE(FieldID, id))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldUpdatedBy, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldTenantID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldVersion, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldDeletedAt, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldOrderID, v))
}

// ShippingOptionID applies equality check predicate on the "shipping_option_id" field. It's identical to ShippingOptionIDEQ.
func ShippingOptionID(v int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldShippingOptionID, v))
}

// TrackingNumber applies equality check predicate on the "tracking_number" field. It's identical to TrackingNumberEQ.
func TrackingNumber(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldTrackingNumber, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotNull(FieldUpdatedBy))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int64) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotNull(FieldTenantID))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLTE(FieldVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotNull(FieldDeletedAt))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldOrderID, vs...))
}

// ShippingOptionIDEQ applies the EQ predicate on the "shipping_option_id" field.
func ShippingOptionIDEQ(v int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldShippingOptionID, v))
}

// ShippingOptionIDNEQ applies the NEQ predicate on the "shipping_option_id" field.
func ShippingOptionIDNEQ(v int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldShippingOptionID, v))
}

// ShippingOptionIDIn applies the In predicate on the "shipping_option_id" field.
func ShippingOptionIDIn(vs ...int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldShippingOptionID, vs...))
}

// ShippingOptionIDNotIn applies the NotIn predicate on the "shipping_option_id" field.
func ShippingOptionIDNotIn(vs ...int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldShippingOptionID, vs...))
}

// ShippingOptionIDGT applies the GT predicate on the "shipping_option_id" field.
func ShippingOptionIDGT(v int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGT(FieldShippingOptionID, v))
}

// ShippingOptionIDGTE applies the GTE predicate on the "shipping_option_id" field.
func ShippingOptionIDGTE(v int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGTE(FieldShippingOptionID, v))
}

// ShippingOptionIDLT applies the LT predicate on the "shipping_option_id" field.
func ShippingOptionIDLT(v int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLT(FieldShippingOptionID, v))
}

// ShippingOptionIDLTE applies the LTE predicate on the "shipping_option_id" field.
func ShippingOptionIDLTE(v int) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLTE(FieldShippingOptionID, v))
}

// ShippingOptionIDIsNil applies the IsNil predicate on the "shipping_option_id" field.
func ShippingOptionIDIsNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIsNull(FieldShippingOptionID))
}

// ShippingOptionIDNotNil applies the NotNil predicate on the "shipping_option_id" field.
func ShippingOptionIDNotNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotNull(FieldShippingOptionID))
}

// TrackingNumberEQ applies the EQ predicate on the "tracking_number" field.
func TrackingNumberEQ(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldTrackingNumber, v))
}

// TrackingNumberNEQ applies the NEQ predicate on the "tracking_number" field.
func TrackingNumberNEQ(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldTrackingNumber, v))
}

// TrackingNumberIn applies the In predicate on the "tracking_number" field.
func TrackingNumberIn(vs ...string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldTrackingNumber, vs...))
}

// TrackingNumberNotIn applies the NotIn predicate on the "tracking_number" field.
func TrackingNumberNotIn(vs ...string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldTrackingNumber, vs...))
}

// TrackingNumberGT applies the GT predicate on the "tracking_number" field.
func TrackingNumberGT(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGT(FieldTrackingNumber, v))
}

// TrackingNumberGTE applies the GTE predicate on the "tracking_number" field.
func TrackingNumberGTE(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldGTE(FieldTrackingNumber, v))
}

// TrackingNumberLT applies the LT predicate on the "tracking_number" field.
func TrackingNumberLT(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLT(FieldTrackingNumber, v))
}

// TrackingNumberLTE applies the LTE predicate on the "tracking_number" field.
func TrackingNumberLTE(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldLTE(FieldTrackingNumber, v))
}

// TrackingNumberContains applies the Contains predicate on the "tracking_number" field.
func TrackingNumberContains(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldContains(FieldTrackingNumber, v))
}

// TrackingNumberHasPrefix applies the HasPrefix predicate on the "tracking_number" field.
func TrackingNumberHasPrefix(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldHasPrefix(FieldTrackingNumber, v))
}

// TrackingNumberHasSuffix applies the HasSuffix predicate on the "tracking_number" field.
func TrackingNumberHasSuffix(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldHasSuffix(FieldTrackingNumber, v))
}

// TrackingNumberIsNil applies the IsNil predicate on the "tracking_number" field.
func TrackingNumberIsNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIsNull(FieldTrackingNumber))
}

// TrackingNumberNotNil applies the NotNil predicate on the "tracking_number" field.
func TrackingNumberNotNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotNull(FieldTrackingNumber))
}

// TrackingNumberEqualFold applies the EqualFold predicate on the "tracking_number" field.
func TrackingNumberEqualFold(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEqualFold(FieldTrackingNumber, v))
}

// TrackingNumberContainsFold applies the ContainsFold predicate on the "tracking_number" field.
func TrackingNumberContainsFold(v string) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldContainsFold(FieldTrackingNumber, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotIn(FieldStatus, vs...))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.Fulfillment {
	return predicate.Fulfillment(sql.FieldNotNull(FieldMetadata))
}

// HasOrder applies the HasEdge predicate on the "order" edge.
func HasOrder() predicate.Fulfillment {
	return predicate.Fulfillment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OrderTable, OrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrderWith applies the HasEdge predicate on the "order" edge with a given conditions (other predicates).
func HasOrderWith(preds ...predicate.Order) predicate.Fulfillment {
	return predicate.Fulfillment(func(s *sql.Selector) {
		step := newOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasItems applies the HasEdge predicate on the "items" edge.
func HasItems() predicate.Fulfillment {
	return predicate.Fulfillment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemsWith applies the HasEdge predicate on the "items" edge with a given conditions (other predicates).
func HasItemsWith(preds ...predicate.FulfillmentItem) predicate.Fulfillment {
	return predicate.Fulfillment(func(s *sql.Selector) {
		step := newItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Fulfillment) predicate.Fulfillment {
	return predicate.Fulfillment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Fulfillment) predicate.Fulfillment {
	return predicate.Fulfillment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Fulfillment) predicate.Fulfillment {
	return predicate.Fulfillment(sql.NotPredicates(p))
}
